import type { Recipe } from "./types";

/** Extra mini-chef recipes (batch 2) */
export const MORE_RECIPES: Recipe[] = [
  {
    id: "pbj-sushi-rolls",
    title: "Peanut Butter & Jelly Sushi Rolls",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "PB&J rolled up and sliced into fun sushi circles — lunchbox magic!",
    emoji: "🍣",
    placeholderColor: "#FFCC80",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "breakfast",
    baseServings: 1,
    imageSrc: "/recipes/pbj-sushi-rolls.svg",
    ingredients: [
      { id: "tortilla", name: "1 flour tortilla" },
      { id: "pb", name: "1 tbsp peanut butter (or alternative)" },
      { id: "jelly", name: "1 tbsp jelly" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Lay the tortilla flat.",
        ingredientIds: ["tortilla"],
      },
      {
        id: "s2",
        instruction: "Spread peanut butter all over it.",
        ingredientIds: ["pb"],
      },
      {
        id: "s3",
        instruction: "Spread jelly on top of the peanut butter.",
        ingredientIds: ["jelly"],
      },
      {
        id: "s4",
        instruction: "Roll the tortilla up tightly like a log.",
        ingredientIds: ["tortilla"],
      },
      {
        id: "s5",
        instruction: "Ask an adult to slice the roll into sushi circles.",
        ingredientIds: [],
        needsAdult: true,
        adultReason: "Slicing needs a knife!",
      },
    ],
  },
  {
    id: "microwave-french-toast-mug",
    title: "Microwave French Toast in a Mug",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Cozy cinnamon French toast that cooks in a mug — breakfast in a flash!",
    emoji: "🍞",
    placeholderColor: "#FFE0B2",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "breakfast",
    baseServings: 1,
    imageSrc: "/recipes/microwave-french-toast-mug.svg",
    ingredients: [
      { id: "bread", name: "1 slice of bread" },
      { id: "egg", name: "1 egg" },
      { id: "milk", name: "2 tbsp milk" },
      { id: "cinnamon", name: "A pinch of cinnamon" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Tear the bread into bite-sized pieces and put them in a mug.",
        ingredientIds: ["bread"],
      },
      {
        id: "s2",
        instruction: "In a small bowl, whisk the egg, milk, and cinnamon.",
        ingredientIds: ["egg", "milk", "cinnamon"],
      },
      {
        id: "s3",
        instruction: "Pour the egg mix over the bread in the mug.",
        ingredientIds: [],
      },
      {
        id: "s4",
        instruction: "Ask an adult to microwave for 1 minute or until the egg is set.",
        timerSeconds: 60,
        timerLabel: "Microwave",
        ingredientIds: [],
        needsAdult: true,
        adultReason: "Hot mug and microwave!",
      },
      {
        id: "s5",
        instruction: "Top with a little syrup if you like!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "breakfast-fruit-pizza",
    title: "Breakfast Fruit Pizza",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "A yogurt-covered crust topped with berry 'pepperoni' — pizza for breakfast!",
    emoji: "🍕",
    placeholderColor: "#F8BBD0",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "breakfast",
    baseServings: 1,
    imageSrc: "/recipes/breakfast-fruit-pizza.svg",
    ingredients: [
      { id: "crust", name: "1 large rice cake or watermelon slice" },
      { id: "yogurt", name: "2 tbsp Greek yogurt" },
      { id: "fruit", name: "Sliced strawberries and blueberries" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Use the rice cake or watermelon slice as your pizza crust.",
        ingredientIds: ["crust"],
      },
      {
        id: "s2",
        instruction: "Spread yogurt over the top like sauce.",
        ingredientIds: ["yogurt"],
      },
      {
        id: "s3",
        instruction: "Decorate with fruit toppings.",
        ingredientIds: ["fruit"],
      },
      {
        id: "s4",
        instruction: "Slice into triangles and eat!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "apple-sandwich-bites",
    title: "Apple Sandwich Bites",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Crunchy apple rings stuffed with peanut butter and granola — sandwich style!",
    emoji: "🍎",
    placeholderColor: "#EF9A9A",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "breakfast",
    baseServings: 1,
    imageSrc: "/recipes/apple-sandwich-bites.svg",
    ingredients: [
      { id: "apple", name: "1 apple" },
      { id: "pb", name: "2 tbsp peanut butter (or alternative)" },
      { id: "granola", name: "1 tbsp granola" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Ask an adult to slice the apple into thick rings and remove the core.",
        ingredientIds: ["apple"],
        needsAdult: true,
        adultReason: "Apple slicing needs a knife!",
      },
      {
        id: "s2",
        instruction: "Spread peanut butter on one apple ring.",
        ingredientIds: ["pb"],
      },
      {
        id: "s3",
        instruction: "Sprinkle granola on the peanut butter.",
        ingredientIds: ["granola"],
      },
      {
        id: "s4",
        instruction: "Place another apple ring on top to make a sandwich!",
        ingredientIds: ["apple"],
      },
    ],
  },
  {
    id: "frozen-yogurt-berry-bark",
    title: "Frozen Yogurt Berry Bark",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Yogurt frozen into snap-apart bark with berries and honey — icy breakfast candy!",
    emoji: "🫐",
    placeholderColor: "#CE93D8",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "breakfast",
    baseServings: 1,
    imageSrc: "/recipes/frozen-yogurt-berry-bark.svg",
    ingredients: [
      { id: "yogurt", name: "1 cup vanilla yogurt" },
      { id: "berries", name: "1/2 cup mixed berries" },
      { id: "honey", name: "1 tsp honey" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Line a tray with wax paper.",
        ingredientIds: [],
      },
      {
        id: "s2",
        instruction: "Spread the yogurt in a thin layer on the paper.",
        ingredientIds: ["yogurt"],
      },
      {
        id: "s3",
        instruction: "Drop berries all over and drizzle with honey.",
        ingredientIds: ["berries", "honey"],
      },
      {
        id: "s4",
        instruction: "Freeze until hard.",
        timerSeconds: 7200,
        timerLabel: "Freeze time",
        ingredientIds: [],
      },
      {
        id: "s5",
        instruction: "Break into pieces and eat like a cold snack!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "cereal-trail-mix-bowl",
    title: "Cereal Trail Mix Bowl",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Cheerios, raisins, and pretzels swimming in milk — crunchy, sweet, and salty!",
    emoji: "🥣",
    placeholderColor: "#FFF59D",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "breakfast",
    baseServings: 1,
    imageSrc: "/recipes/cereal-trail-mix-bowl.svg",
    ingredients: [
      { id: "cheerios", name: "1/2 cup Cheerios" },
      { id: "raisins", name: "1/4 cup raisins" },
      { id: "pretzels", name: "1/4 cup pretzels" },
      { id: "milk", name: "1/2 cup milk" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Mix the cereal, raisins, and pretzels in a bowl.",
        ingredientIds: ["cheerios", "raisins", "pretzels"],
      },
      {
        id: "s2",
        instruction: "Pour the milk over the top.",
        ingredientIds: ["milk"],
      },
      {
        id: "s3",
        instruction: "Dig into your crunchy breakfast trail mix!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "banana-sushi-cereal",
    title: "Banana Sushi",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "A nut-butter banana rolled in crispy cereal, sliced into sushi rounds!",
    emoji: "🍌",
    placeholderColor: "#FFE566",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "breakfast",
    baseServings: 1,
    imageSrc: "/recipes/banana-sushi-cereal.svg",
    ingredients: [
      { id: "banana", name: "1 banana" },
      { id: "butter", name: "1 tbsp almond or peanut butter" },
      { id: "cereal", name: "2 tbsp crispy rice cereal" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Peel the banana.",
        ingredientIds: ["banana"],
      },
      {
        id: "s2",
        instruction: "Spread the nut butter all over the outside.",
        ingredientIds: ["butter"],
      },
      {
        id: "s3",
        instruction: "Roll the banana in the cereal so it sticks.",
        ingredientIds: ["cereal"],
      },
      {
        id: "s4",
        instruction: "Ask an adult to slice into sushi rounds.",
        ingredientIds: [],
        needsAdult: true,
        adultReason: "Slicing needs a knife!",
      },
    ],
  },
  {
    id: "overnight-chia-pudding",
    title: "Overnight Chia Pudding",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Tiny chia seeds turn into thick pudding overnight — morning magic in a jar!",
    emoji: "🫙",
    placeholderColor: "#B39DDB",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "breakfast",
    baseServings: 1,
    imageSrc: "/recipes/overnight-chia-pudding.svg",
    ingredients: [
      { id: "milk", name: "1/2 cup milk" },
      { id: "chia", name: "2 tbsp chia seeds" },
      { id: "maple", name: "1 tsp maple syrup" },
      { id: "vanilla", name: "1/4 tsp vanilla" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Mix all the ingredients in a small jar.",
        ingredientIds: ["milk", "chia", "maple", "vanilla"],
      },
      {
        id: "s2",
        instruction: "Stir really well so the seeds don't clump.",
        ingredientIds: [],
      },
      {
        id: "s3",
        instruction: "Put the lid on and leave it in the fridge overnight.",
        timerSeconds: 300,
        timerLabel: "Optional chill — or skip & wait overnight",
        ingredientIds: [],
      },
      {
        id: "s4",
        instruction: "In the morning, enjoy your thick pudding!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "ham-cheese-breakfast-croissants",
    title: "Ham & Cheese Breakfast Croissants",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Flaky croissant stuffed with ham and melty cheese — bakery vibes at home!",
    emoji: "🥐",
    placeholderColor: "#FFCC80",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "breakfast",
    baseServings: 1,
    imageSrc: "/recipes/ham-cheese-breakfast-croissants.svg",
    ingredients: [
      { id: "croissant", name: "1 pre-made croissant" },
      { id: "ham", name: "1 slice of ham" },
      { id: "cheese", name: "1 slice of cheese" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Ask an adult to carefully slice the croissant in half.",
        ingredientIds: ["croissant"],
        needsAdult: true,
        adultReason: "Slicing the croissant needs help!",
      },
      {
        id: "s2",
        instruction: "Put the ham and cheese inside.",
        ingredientIds: ["ham", "cheese"],
      },
      {
        id: "s3",
        instruction: "Eat cold, or ask an adult to warm 20 seconds to melt the cheese.",
        timerSeconds: 20,
        timerLabel: "Warm croissant",
        ingredientIds: [],
        needsAdult: true,
        adultReason: "Microwave is hot!",
      },
    ],
  },
  {
    id: "hard-boiled-egg-chicks",
    title: "Hard Boiled Egg \"Chicks\"",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Peeled eggs dressed up as little chicks with carrot beaks — almost too cute to eat!",
    emoji: "🐣",
    placeholderColor: "#FFF9C4",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "breakfast",
    baseServings: 1,
    imageSrc: "/recipes/hard-boiled-egg-chicks.svg",
    ingredients: [
      { id: "eggs", name: "2 hard-boiled eggs (pre-cooked)" },
      { id: "carrot", name: "1 small carrot" },
      { id: "eyes", name: "2 peppercorns or olive bits" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Peel the hard-boiled eggs.",
        ingredientIds: ["eggs"],
      },
      {
        id: "s2",
        instruction: "Ask an adult to cut tiny carrot triangles for a beak and feet.",
        ingredientIds: ["carrot"],
        needsAdult: true,
        adultReason: "Carrot cutting needs a knife!",
      },
      {
        id: "s3",
        instruction: "Press the carrot beak and olive eyes into the egg to make a chick!",
        ingredientIds: ["eyes"],
      },
    ],
  },
  {
    id: "bagel-fruit-flowers",
    title: "Bagel with Fruit Flowers",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Cream-cheese bagels decorated with strawberry petals — garden on toast!",
    emoji: "🌸",
    placeholderColor: "#F48FB1",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "breakfast",
    baseServings: 1,
    imageSrc: "/recipes/bagel-fruit-flowers.svg",
    ingredients: [
      { id: "bagel", name: "1 mini bagel" },
      { id: "cream", name: "2 tbsp cream cheese" },
      { id: "fruit", name: "Sliced strawberries and grapes" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Ask an adult to toast the bagel.",
        ingredientIds: ["bagel"],
        needsAdult: true,
        adultReason: "Toasters get hot!",
      },
      {
        id: "s2",
        instruction: "Spread cream cheese on both halves.",
        ingredientIds: ["cream"],
      },
      {
        id: "s3",
        instruction: "Arrange strawberry slices like petals and a grape for the center.",
        ingredientIds: ["fruit"],
      },
    ],
  },
  {
    id: "breakfast-burrito-wrap",
    title: "Breakfast Burrito Wrap",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Scrambled egg and cheese rolled in a tortilla — a handheld morning burrito!",
    emoji: "🌯",
    placeholderColor: "#FFB74D",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "breakfast",
    baseServings: 1,
    imageSrc: "/recipes/breakfast-burrito-wrap.svg",
    ingredients: [
      { id: "tortilla", name: "1 small tortilla" },
      { id: "egg", name: "1 scrambled egg (pre-cooked)" },
      { id: "cheese", name: "2 tbsp shredded cheese" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Put the scrambled egg in the middle of the tortilla.",
        ingredientIds: ["tortilla", "egg"],
      },
      {
        id: "s2",
        instruction: "Sprinkle cheese on top.",
        ingredientIds: ["cheese"],
      },
      {
        id: "s3",
        instruction: "Fold the sides in and roll it up like a burrito.",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "pita-bread-pizzas",
    title: "Pita Bread Pizzas",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Crispy pita crusts with sauce and bubbly cheese — personal pizzas in minutes!",
    emoji: "🫓",
    placeholderColor: "#FF8A65",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dinner",
    baseServings: 1,
    imageSrc: "/recipes/pita-bread-pizzas.svg",
    ingredients: [
      { id: "pita", name: "1 pita bread" },
      { id: "sauce", name: "2 tbsp tomato sauce" },
      { id: "cheese", name: "1/2 cup shredded cheese" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Lay the pita flat on a baking sheet.",
        ingredientIds: ["pita"],
      },
      {
        id: "s2",
        instruction: "Spread sauce and sprinkle cheese.",
        ingredientIds: ["sauce", "cheese"],
      },
      {
        id: "s3",
        instruction: "Ask an adult to bake at 350°F for 5–7 minutes until bubbly.",
        timerSeconds: 360,
        timerLabel: "Bake pita pizza",
        ingredientIds: [],
        needsAdult: true,
        adultReason: "Ovens are hot!",
      },
    ],
  },
  {
    id: "ham-cheese-sliders",
    title: "Ham & Cheese Sliders",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Tiny dinner-roll sandwiches stacked with ham and Swiss — lunchbox heroes!",
    emoji: "🥪",
    placeholderColor: "#FFCCBC",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dinner",
    baseServings: 1,
    imageSrc: "/recipes/ham-cheese-sliders.svg",
    ingredients: [
      { id: "rolls", name: "2 small dinner rolls" },
      { id: "ham", name: "2 slices of ham" },
      { id: "cheese", name: "2 slices of Swiss cheese" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Pull the rolls apart and open them.",
        ingredientIds: ["rolls"],
      },
      {
        id: "s2",
        instruction: "Put ham and cheese inside each one.",
        ingredientIds: ["ham", "cheese"],
      },
      {
        id: "s3",
        instruction: "Pack cold in a lunchbox or eat right away!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "rainbow-pasta-salad",
    title: "Rainbow Pasta Salad",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Cold pasta tossed with peas, carrots, and zesty dressing — a colorful bowl!",
    emoji: "🌈",
    placeholderColor: "#81D4FA",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dinner",
    baseServings: 1,
    imageSrc: "/recipes/rainbow-pasta-salad.svg",
    ingredients: [
      { id: "pasta", name: "1 cup cooked rotini pasta (cold)" },
      { id: "peas", name: "1/4 cup peas" },
      { id: "carrots", name: "1/4 cup chopped carrots" },
      { id: "dressing", name: "2 tbsp Italian dressing" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Put the cold pasta in a big bowl.",
        ingredientIds: ["pasta"],
      },
      {
        id: "s2",
        instruction: "Add the peas and carrots.",
        ingredientIds: ["peas", "carrots"],
      },
      {
        id: "s3",
        instruction: "Pour the dressing over and stir it all up.",
        ingredientIds: ["dressing"],
      },
    ],
  },
  {
    id: "tuna-salad-boats",
    title: "Tuna Salad Boats",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Celery boats filled with creamy tuna salad — sail into snack time!",
    emoji: "⛵",
    placeholderColor: "#80CBC4",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dinner",
    baseServings: 1,
    imageSrc: "/recipes/tuna-salad-boats.svg",
    ingredients: [
      { id: "tuna", name: "1 can of tuna (drained)" },
      { id: "mayo", name: "1 tbsp mayo" },
      { id: "celery", name: "2 large celery stalks" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Mix the tuna and mayo in a small bowl.",
        ingredientIds: ["tuna", "mayo"],
      },
      {
        id: "s2",
        instruction: "Wash the celery and dry it.",
        ingredientIds: ["celery"],
      },
      {
        id: "s3",
        instruction: "Spoon the tuna mix into the celery boats.",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "hummus-veggie-wraps",
    title: "Hummus & Veggie Wraps",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Creamy hummus, lettuce, and cucumber rolled tight — fresh and crunchy!",
    emoji: "🥬",
    placeholderColor: "#C5E1A5",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dinner",
    baseServings: 1,
    imageSrc: "/recipes/hummus-veggie-wraps.svg",
    ingredients: [
      { id: "tortilla", name: "1 tortilla" },
      { id: "hummus", name: "2 tbsp hummus" },
      { id: "lettuce", name: "Shredded lettuce" },
      { id: "cucumber", name: "Thin cucumber slices" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Spread hummus all over the tortilla.",
        ingredientIds: ["tortilla", "hummus"],
      },
      {
        id: "s2",
        instruction: "Lay the lettuce and cucumbers on top.",
        ingredientIds: ["lettuce", "cucumber"],
      },
      {
        id: "s3",
        instruction: "Roll it up tight and enjoy!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "mini-bagel-turkey-burgers",
    title: "Mini Bagel Turkey Burgers",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Tiny bagel 'burgers' with turkey, cheese, and mustard — big flavor, small size!",
    emoji: "🥯",
    placeholderColor: "#FFAB91",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dinner",
    baseServings: 1,
    imageSrc: "/recipes/mini-bagel-turkey-burgers.svg",
    ingredients: [
      { id: "bagel", name: "1 mini bagel" },
      { id: "turkey", name: "2 slices of deli turkey" },
      { id: "cheese", name: "1 slice of cheese" },
      { id: "mustard", name: "1 tsp mustard" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Spread mustard on the bagel.",
        ingredientIds: ["bagel", "mustard"],
      },
      {
        id: "s2",
        instruction: "Fold the turkey and cheese to fit on the small bagel.",
        ingredientIds: ["turkey", "cheese"],
      },
      {
        id: "s3",
        instruction: "Close the burger and take a big bite!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "taco-salad-crunch-bowls",
    title: "Taco Salad Crunch Bowls",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Crushed chips topped with beans, lettuce, and cheese — a crunchy taco bowl!",
    emoji: "🥗",
    placeholderColor: "#FFD54F",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dinner",
    baseServings: 1,
    imageSrc: "/recipes/taco-salad-crunch-bowls.svg",
    ingredients: [
      { id: "chips", name: "1 handful of tortilla chips" },
      { id: "beans", name: "1/4 cup black beans" },
      { id: "lettuce", name: "1/4 cup shredded lettuce" },
      { id: "cheese", name: "2 tbsp shredded cheese" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Crush the chips slightly and put them in a bowl.",
        ingredientIds: ["chips"],
      },
      {
        id: "s2",
        instruction: "Top with beans, lettuce, and cheese.",
        ingredientIds: ["beans", "lettuce", "cheese"],
      },
      {
        id: "s3",
        instruction: "Mix it up for a crunchy salad!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "pizza-hawaiian-sliders",
    title: "Pizza Hawaiian Sliders",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Sweet Hawaiian rolls with pepperoni and melty cheese — pizza party sliders!",
    emoji: "🍕",
    placeholderColor: "#FF8A80",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dinner",
    baseServings: 1,
    imageSrc: "/recipes/pizza-hawaiian-sliders.svg",
    ingredients: [
      { id: "rolls", name: "2 Hawaiian sweet rolls" },
      { id: "pepperoni", name: "2 slices of pepperoni" },
      { id: "cheese", name: "1 cheese stick (cut in half)" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Open the rolls.",
        ingredientIds: ["rolls"],
      },
      {
        id: "s2",
        instruction: "Put a pepperoni slice and half a cheese stick in each.",
        ingredientIds: ["pepperoni", "cheese"],
      },
      {
        id: "s3",
        instruction: "Ask an adult to warm in the microwave for 15 seconds.",
        timerSeconds: 15,
        timerLabel: "Melt cheese",
        ingredientIds: [],
        needsAdult: true,
        adultReason: "Microwave melts cheese — adult help!",
      },
    ],
  },
  {
    id: "chicken-salad-grapes",
    title: "Chicken Salad Grapes",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Creamy chicken salad with sweet grape halves — scoop it up with crackers!",
    emoji: "🍇",
    placeholderColor: "#E1BEE7",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dinner",
    baseServings: 1,
    imageSrc: "/recipes/chicken-salad-grapes.svg",
    ingredients: [
      { id: "chicken", name: "1/2 cup canned chicken (drained)" },
      { id: "mayo", name: "1 tbsp mayo" },
      { id: "grapes", name: "5 large grapes (cut in half)" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Mix the chicken and mayo.",
        ingredientIds: ["chicken", "mayo"],
      },
      {
        id: "s2",
        instruction: "Stir in the grape halves for a sweet and savory lunch.",
        ingredientIds: ["grapes"],
      },
      {
        id: "s3",
        instruction: "Eat with crackers!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "cheese-meat-kabobs",
    title: "Cheese & Meat Kabobs",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Cheese cubes, ham, and cherry tomatoes on a stick — party food you build!",
    emoji: "🍢",
    placeholderColor: "#FFCDD2",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dinner",
    baseServings: 1,
    imageSrc: "/recipes/cheese-meat-kabobs.svg",
    ingredients: [
      { id: "cheese", name: "Cheese cubes" },
      { id: "ham", name: "Folded ham slices" },
      { id: "tomatoes", name: "Cherry tomatoes" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Carefully slide a cheese cube onto a skewer. Watch the sharp point!",
        ingredientIds: ["cheese"],
      },
      {
        id: "s2",
        instruction: "Add a piece of ham, then a tomato.",
        ingredientIds: ["ham", "tomatoes"],
      },
      {
        id: "s3",
        instruction: "Repeat until the stick is full!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "veggie-sushi-rolls",
    title: "Veggie Sushi Rolls",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Rice and cucumber rolled in nori or a tortilla — homemade veggie sushi!",
    emoji: "🍱",
    placeholderColor: "#A5D6A7",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dinner",
    baseServings: 1,
    imageSrc: "/recipes/veggie-sushi-rolls.svg",
    ingredients: [
      { id: "wrap", name: "1 sheet of nori or a tortilla" },
      { id: "rice", name: "1/2 cup cooked rice" },
      { id: "cucumber", name: "Thin cucumber strips" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Lay the nori or tortilla flat.",
        ingredientIds: ["wrap"],
      },
      {
        id: "s2",
        instruction: "Spread the rice in a thin layer.",
        ingredientIds: ["rice"],
      },
      {
        id: "s3",
        instruction: "Put the cucumber strips in a line.",
        ingredientIds: ["cucumber"],
      },
      {
        id: "s4",
        instruction: "Roll it up, then ask an adult to slice into rounds.",
        ingredientIds: [],
        needsAdult: true,
        adultReason: "Slicing sushi needs a knife!",
      },
    ],
  },
  {
    id: "microwave-bean-cheese-burrito",
    title: "Microwave Bean & Cheese Burrito",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Warm refried beans and cheese in a soft tortilla — melty burrito bliss!",
    emoji: "🌮",
    placeholderColor: "#FFB74D",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dinner",
    baseServings: 1,
    imageSrc: "/recipes/microwave-bean-cheese-burrito.svg",
    ingredients: [
      { id: "tortilla", name: "1 tortilla" },
      { id: "beans", name: "1/4 cup refried beans" },
      { id: "cheese", name: "2 tbsp shredded cheese" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Spread the beans on the tortilla.",
        ingredientIds: ["tortilla", "beans"],
      },
      {
        id: "s2",
        instruction: "Sprinkle cheese on top.",
        ingredientIds: ["cheese"],
      },
      {
        id: "s3",
        instruction: "Ask an adult to microwave for 30 seconds.",
        timerSeconds: 30,
        timerLabel: "Warm burrito",
        ingredientIds: [],
        needsAdult: true,
        adultReason: "Hot burrito — adult microwave help!",
      },
      {
        id: "s4",
        instruction: "Roll it up carefully — it will be hot!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "mini-corn-dogs",
    title: "Mini Corn Dogs",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Bite-sized corn dogs heated until hot — fair-food fun at home!",
    emoji: "🌭",
    placeholderColor: "#FFCC80",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dinner",
    baseServings: 1,
    imageSrc: "/recipes/mini-corn-dogs.svg",
    ingredients: [
      { id: "corndogs", name: "4 frozen mini corn dogs" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Ask an adult to place the corn dogs on a microwave-safe plate.",
        ingredientIds: ["corndogs"],
        needsAdult: true,
        adultReason: "Microwave cooking needs adult help!",
      },
      {
        id: "s2",
        instruction: "Microwave for 45–60 seconds until hot all the way through.",
        timerSeconds: 60,
        timerLabel: "Heat corn dogs",
        ingredientIds: [],
        needsAdult: true,
        adultReason: "Hot food from the microwave!",
      },
      {
        id: "s3",
        instruction: "Let them cool for a minute before eating.",
        timerSeconds: 60,
        timerLabel: "Cool down",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "no-bake-pb-bars",
    title: "No-Bake Peanut Butter Bars",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Peanut butter, honey, and graham crumbs pressed into chill-and-slice bars!",
    emoji: "🟫",
    placeholderColor: "#D7CCC8",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dessert",
    baseServings: 1,
    imageSrc: "/recipes/no-bake-pb-bars.svg",
    ingredients: [
      { id: "pb", name: "1/2 cup peanut butter (or alternative)" },
      { id: "honey", name: "1/4 cup honey" },
      { id: "crumbs", name: "1 cup graham cracker crumbs" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Mix everything in a bowl until it's like dough.",
        ingredientIds: ["pb", "honey", "crumbs"],
      },
      {
        id: "s2",
        instruction: "Press it into a small square pan.",
        ingredientIds: [],
      },
      {
        id: "s3",
        instruction: "Put it in the fridge until firm.",
        timerSeconds: 3600,
        timerLabel: "Chill bars",
        ingredientIds: [],
      },
      {
        id: "s4",
        instruction: "Cut into small squares.",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "fruit-salsa-cinnamon-chips",
    title: "Fruit Salsa & Cinnamon Chips",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Chopped fruit salsa scooped up with crunchy cinnamon-sugar chips!",
    emoji: "🍎",
    placeholderColor: "#FFAB91",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dessert",
    baseServings: 1,
    imageSrc: "/recipes/fruit-salsa-cinnamon-chips.svg",
    ingredients: [
      { id: "apple", name: "1 apple (finely chopped)" },
      { id: "berries", name: "5 strawberries (finely chopped)" },
      { id: "tortilla", name: "1 tortilla" },
      { id: "cinnamon", name: "A sprinkle of cinnamon and sugar" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Mix the chopped fruit in a bowl.",
        ingredientIds: ["apple", "berries"],
      },
      {
        id: "s2",
        instruction: "Ask an adult to cut the tortilla into triangles and toast until crunchy.",
        timerSeconds: 480,
        timerLabel: "Toast chips",
        ingredientIds: ["tortilla"],
        needsAdult: true,
        adultReason: "Oven toasting needs adult help!",
      },
      {
        id: "s3",
        instruction: "Sprinkle cinnamon and sugar on the warm chips.",
        ingredientIds: ["cinnamon"],
      },
      {
        id: "s4",
        instruction: "Use the chips to scoop up the fruit salsa!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "smores-marshmallow-pops",
    title: "S'mores Marshmallow Pops",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Marshmallows dipped in chocolate and graham crumbs — campfire pops!",
    emoji: "🍡",
    placeholderColor: "#BCAAA4",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dessert",
    baseServings: 1,
    imageSrc: "/recipes/smores-marshmallow-pops.svg",
    ingredients: [
      { id: "mallows", name: "4 large marshmallows" },
      { id: "chips", name: "1/4 cup chocolate chips" },
      { id: "graham", name: "2 graham crackers (crushed)" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Put a stick into each marshmallow.",
        ingredientIds: ["mallows"],
      },
      {
        id: "s2",
        instruction: "Ask an adult to melt the chocolate in the microwave.",
        timerSeconds: 30,
        timerLabel: "Melt chocolate",
        ingredientIds: ["chips"],
        needsAdult: true,
        adultReason: "Hot melted chocolate!",
      },
      {
        id: "s3",
        instruction: "Dip the marshmallow in chocolate, then roll in graham crumbs.",
        ingredientIds: ["graham"],
      },
    ],
  },
  {
    id: "edible-jello-play-dough",
    title: "Edible Jello Play Dough",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Colorful dough you can squish, sculpt, and snack on — play then eat!",
    emoji: "🎨",
    placeholderColor: "#F48FB1",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dessert",
    baseServings: 1,
    imageSrc: "/recipes/edible-jello-play-dough.svg",
    ingredients: [
      { id: "flour", name: "1 cup flour" },
      { id: "jello", name: "1 pack of Jello powder" },
      { id: "water", name: "1/2 cup warm water" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Mix the flour and Jello powder.",
        ingredientIds: ["flour", "jello"],
      },
      {
        id: "s2",
        instruction: "Add the warm water and stir until it's like dough.",
        ingredientIds: ["water"],
      },
      {
        id: "s3",
        instruction: "Knead it with clean hands — play with it, then eat it!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "chocolate-dipped-pretzels",
    title: "Chocolate Dipped Pretzels",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Salty pretzel rods dipped in chocolate and sprinkles — sweet and crunchy!",
    emoji: "🥨",
    placeholderColor: "#A1887F",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dessert",
    baseServings: 1,
    imageSrc: "/recipes/chocolate-dipped-pretzels.svg",
    ingredients: [
      { id: "pretzels", name: "10 pretzel rods" },
      { id: "chips", name: "1/2 cup chocolate chips" },
      { id: "sprinkles", name: "Sprinkles" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Ask an adult to melt the chocolate in a tall glass in the microwave.",
        timerSeconds: 45,
        timerLabel: "Melt chocolate",
        ingredientIds: ["chips"],
        needsAdult: true,
        adultReason: "Hot melted chocolate!",
      },
      {
        id: "s2",
        instruction: "Dip half of each pretzel rod into the chocolate.",
        ingredientIds: ["pretzels"],
      },
      {
        id: "s3",
        instruction: "Shake on sprinkles and let them dry on wax paper.",
        ingredientIds: ["sprinkles"],
      },
    ],
  },
  {
    id: "frozen-grapes",
    title: "Frozen Grapes",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Grapes frozen into tiny sorbet balls — the simplest cold treat ever!",
    emoji: "🍇",
    placeholderColor: "#CE93D8",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dessert",
    baseServings: 1,
    imageSrc: "/recipes/frozen-grapes.svg",
    ingredients: [
      { id: "grapes", name: "1 bunch of grapes" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Wash the grapes and pull them off the stems.",
        ingredientIds: ["grapes"],
      },
      {
        id: "s2",
        instruction: "Put them in a plastic bag and freeze them.",
        timerSeconds: 7200,
        timerLabel: "Freeze grapes",
        ingredientIds: [],
      },
      {
        id: "s3",
        instruction: "Eat them like tiny fruit sorbet balls!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "yogurt-covered-blueberries",
    title: "Yogurt Covered Blueberries",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Blueberries dipped in yogurt and frozen — little frosty berry gems!",
    emoji: "🔵",
    placeholderColor: "#90CAF9",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dessert",
    baseServings: 1,
    imageSrc: "/recipes/yogurt-covered-blueberries.svg",
    ingredients: [
      { id: "berries", name: "1/2 cup blueberries" },
      { id: "yogurt", name: "1/2 cup vanilla yogurt" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Use a toothpick to dip each blueberry into the yogurt.",
        ingredientIds: ["berries", "yogurt"],
      },
      {
        id: "s2",
        instruction: "Place them on a tray with wax paper.",
        ingredientIds: [],
      },
      {
        id: "s3",
        instruction: "Freeze until the yogurt is hard.",
        timerSeconds: 3600,
        timerLabel: "Freeze berries",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "no-bake-cheesecake-jars",
    title: "No-Bake Cheesecake Jars",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Creamy cheesecake layers in a jar with graham crumbs and a berry on top!",
    emoji: "🧁",
    placeholderColor: "#FCE4EC",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dessert",
    baseServings: 1,
    imageSrc: "/recipes/no-bake-cheesecake-jars.svg",
    ingredients: [
      { id: "crumbs", name: "1/4 cup graham cracker crumbs" },
      { id: "cream", name: "1/2 cup cream cheese (soft)" },
      { id: "sugar", name: "2 tbsp powdered sugar" },
      { id: "whip", name: "1/4 cup whipped cream" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Put crumbs in the bottom of a small jar.",
        ingredientIds: ["crumbs"],
      },
      {
        id: "s2",
        instruction: "Mix the cream cheese, sugar, and whipped cream until smooth.",
        ingredientIds: ["cream", "sugar", "whip"],
      },
      {
        id: "s3",
        instruction: "Spoon the mix over the crumbs.",
        ingredientIds: [],
      },
      {
        id: "s4",
        instruction: "Top with a berry!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "popcorn-trail-mix",
    title: "Popcorn Trail Mix",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Popcorn, M&Ms, and mini pretzels — the perfect movie-night mix!",
    emoji: "🍿",
    placeholderColor: "#FFF59D",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dessert",
    baseServings: 1,
    imageSrc: "/recipes/popcorn-trail-mix.svg",
    ingredients: [
      { id: "popcorn", name: "2 cups popped popcorn" },
      { id: "candy", name: "1/4 cup M&Ms" },
      { id: "pretzels", name: "1/4 cup mini pretzels" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Mix everything in a big bowl.",
        ingredientIds: ["popcorn", "candy", "pretzels"],
      },
      {
        id: "s2",
        instruction: "Grab a handful for movie night!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "banana-split-bites",
    title: "Banana Split Bites",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Banana rounds with chocolate, nuts, and cherry bits — mini banana splits!",
    emoji: "🍒",
    placeholderColor: "#FFECB3",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dessert",
    baseServings: 1,
    imageSrc: "/recipes/banana-split-bites.svg",
    ingredients: [
      { id: "banana", name: "1 banana" },
      { id: "syrup", name: "1 tbsp chocolate syrup" },
      { id: "nuts", name: "1 tbsp chopped peanuts (or seeds)" },
      { id: "cherry", name: "1 maraschino cherry" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Ask an adult to slice the banana into thick rounds.",
        ingredientIds: ["banana"],
        needsAdult: true,
        adultReason: "Banana slicing may need a knife!",
      },
      {
        id: "s2",
        instruction: "Drizzle a little chocolate on each round.",
        ingredientIds: ["syrup"],
      },
      {
        id: "s3",
        instruction: "Sprinkle with nuts and put a tiny piece of cherry on top.",
        ingredientIds: ["nuts", "cherry"],
      },
    ],
  },
  {
    id: "rice-cake-animal-faces",
    title: "Rice Cake Animal Faces",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Nut butter rice cakes turned into lions, bears, or cats with fruit faces!",
    emoji: "🐯",
    placeholderColor: "#FFE082",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dessert",
    baseServings: 1,
    imageSrc: "/recipes/rice-cake-animal-faces.svg",
    ingredients: [
      { id: "cake", name: "1 rice cake" },
      { id: "butter", name: "1 tbsp nut butter" },
      { id: "fruit", name: "Banana, blueberry, and strawberry slices" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Spread nut butter on the rice cake.",
        ingredientIds: ["cake", "butter"],
      },
      {
        id: "s2",
        instruction: "Use banana for ears, blueberries for eyes, and strawberry for a nose.",
        ingredientIds: ["fruit"],
      },
      {
        id: "s3",
        instruction: "Make a lion, a bear, or a cat!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "graham-ice-cream-sandwiches",
    title: "Graham Cracker Ice Cream Sandwiches",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Soft ice cream squished between graham crackers, then frozen firm!",
    emoji: "🍦",
    placeholderColor: "#D7CCC8",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dessert",
    baseServings: 1,
    imageSrc: "/recipes/graham-ice-cream-sandwiches.svg",
    ingredients: [
      { id: "graham", name: "2 graham cracker squares" },
      { id: "icecream", name: "1 scoop of softened ice cream" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Put the ice cream on one graham cracker.",
        ingredientIds: ["graham", "icecream"],
      },
      {
        id: "s2",
        instruction: "Press the other cracker on top.",
        ingredientIds: ["graham"],
      },
      {
        id: "s3",
        instruction: "Freeze until the ice cream is firm again.",
        timerSeconds: 3600,
        timerLabel: "Freeze sandwich",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "simple-fruit-leather-rolls",
    title: "Simple Fruit Leather Rolls",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Applesauce baked thin into peel-and-roll fruit leather — chewy and sweet!",
    emoji: "📜",
    placeholderColor: "#FFAB91",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "dessert",
    baseServings: 1,
    imageSrc: "/recipes/simple-fruit-leather-rolls.svg",
    ingredients: [
      { id: "applesauce", name: "1 cup applesauce" },
      { id: "honey", name: "1 tsp honey" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Ask an adult to spread applesauce thin on a silicone-lined baking sheet.",
        ingredientIds: ["applesauce", "honey"],
        needsAdult: true,
        adultReason: "Oven prep needs adult help!",
      },
      {
        id: "s2",
        instruction: "Ask an adult to bake on the lowest setting 2–3 hours until not sticky.",
        timerSeconds: 7200,
        timerLabel: "Bake leather (or skip & wait)",
        ingredientIds: [],
        needsAdult: true,
        adultReason: "Long oven time — grown-up job!",
      },
      {
        id: "s3",
        instruction: "Peel it off and roll it up!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "watermelon-slushie",
    title: "Watermelon Slushie",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Frozen watermelon blended into a snowy pink slush — sip with a spoon!",
    emoji: "🍉",
    placeholderColor: "#EF9A9A",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "drinks",
    baseServings: 1,
    imageSrc: "/recipes/watermelon-slushie.svg",
    ingredients: [
      { id: "melon", name: "2 cups frozen watermelon chunks" },
      { id: "water", name: "1/2 cup water" },
      { id: "lime", name: "1 tsp lime juice" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Put everything in the blender.",
        ingredientIds: ["melon", "water", "lime"],
      },
      {
        id: "s2",
        instruction: "Ask an adult to blend until snowy.",
        timerSeconds: 30,
        timerLabel: "Blend slushie",
        ingredientIds: [],
        needsAdult: true,
        adultReason: "Blenders need adult hands!",
      },
      {
        id: "s3",
        instruction: "Pour into a glass and drink with a spoon!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "orange-creamsicle-smoothie",
    title: "Orange Creamsicle Smoothie",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Orange juice and vanilla yogurt blended icy — tastes like a creamsicle!",
    emoji: "🍊",
    placeholderColor: "#FFCC80",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "drinks",
    baseServings: 1,
    imageSrc: "/recipes/orange-creamsicle-smoothie.svg",
    ingredients: [
      { id: "juice", name: "1/2 cup orange juice" },
      { id: "yogurt", name: "1/2 cup vanilla yogurt" },
      { id: "ice", name: "1/2 cup ice" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Put all ingredients in the blender.",
        ingredientIds: ["juice", "yogurt", "ice"],
      },
      {
        id: "s2",
        instruction: "Ask an adult to blend until smooth.",
        timerSeconds: 30,
        timerLabel: "Blend smoothie",
        ingredientIds: [],
        needsAdult: true,
        adultReason: "Blenders need adult hands!",
      },
      {
        id: "s3",
        instruction: "Pour and enjoy your creamsicle sip!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "homemade-cold-apple-cider",
    title: "Homemade Cold Apple Cider",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Chilled apple juice with cinnamon and an orange slice — fancy fall vibes!",
    emoji: "🍎",
    placeholderColor: "#FFCC80",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "drinks",
    baseServings: 1,
    imageSrc: "/recipes/homemade-cold-apple-cider.svg",
    ingredients: [
      { id: "juice", name: "1 cup apple juice" },
      { id: "cinnamon", name: "A tiny pinch of cinnamon" },
      { id: "orange", name: "1 orange slice" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Pour the apple juice into a glass.",
        ingredientIds: ["juice"],
      },
      {
        id: "s2",
        instruction: "Stir in the cinnamon.",
        ingredientIds: ["cinnamon"],
      },
      {
        id: "s3",
        instruction: "Add the orange slice for a fancy look.",
        ingredientIds: ["orange"],
      },
    ],
  },
  {
    id: "blueberry-lemonade",
    title: "Blueberry Lemonade",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Mashed blueberries turn lemonade purple — science experiment you can drink!",
    emoji: "💜",
    placeholderColor: "#CE93D8",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "drinks",
    baseServings: 1,
    imageSrc: "/recipes/blueberry-lemonade.svg",
    ingredients: [
      { id: "lemonade", name: "1 cup lemonade" },
      { id: "berries", name: "5 blueberries (mashed)" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Mash the blueberries in the bottom of a glass with a spoon.",
        ingredientIds: ["berries"],
      },
      {
        id: "s2",
        instruction: "Pour the lemonade over the top.",
        ingredientIds: ["lemonade"],
      },
      {
        id: "s3",
        instruction: "Watch the drink turn purple!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "pineapple-coconut-mocktail",
    title: "Pineapple Coconut Mocktail",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Pineapple juice and coconut milk over ice — a tropical mocktail!",
    emoji: "🏝️",
    placeholderColor: "#FFF59D",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "drinks",
    baseServings: 1,
    imageSrc: "/recipes/pineapple-coconut-mocktail.svg",
    ingredients: [
      { id: "pineapple", name: "1/2 cup pineapple juice" },
      { id: "coconut", name: "1/4 cup coconut milk" },
      { id: "ice", name: "Ice" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Put ice in a glass.",
        ingredientIds: ["ice"],
      },
      {
        id: "s2",
        instruction: "Pour in the juice and coconut milk.",
        ingredientIds: ["pineapple", "coconut"],
      },
      {
        id: "s3",
        instruction: "Stir it up for a tropical treat!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "chocolate-banana-milk",
    title: "Chocolate Banana Milk",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Blended banana and chocolate syrup make extra-creamy chocolate milk!",
    emoji: "🥛",
    placeholderColor: "#BCAAA4",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "drinks",
    baseServings: 1,
    imageSrc: "/recipes/chocolate-banana-milk.svg",
    ingredients: [
      { id: "milk", name: "1 cup milk" },
      { id: "banana", name: "1/2 banana" },
      { id: "syrup", name: "1 tbsp chocolate syrup" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Put everything in the blender.",
        ingredientIds: ["milk", "banana", "syrup"],
      },
      {
        id: "s2",
        instruction: "Ask an adult to blend until the banana disappears.",
        timerSeconds: 30,
        timerLabel: "Blend milk",
        ingredientIds: [],
        needsAdult: true,
        adultReason: "Blenders need adult hands!",
      },
      {
        id: "s3",
        instruction: "Pour and sip your creamy chocolate milk!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "grape-juice-spritzer",
    title: "Grape Juice Spritzer",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Grape juice topped with sparkling water — bubbly purple fun!",
    emoji: "🫧",
    placeholderColor: "#BA68C8",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "drinks",
    baseServings: 1,
    imageSrc: "/recipes/grape-juice-spritzer.svg",
    ingredients: [
      { id: "grape", name: "1/2 cup grape juice" },
      { id: "sparkle", name: "1/2 cup sparkling water" },
      { id: "ice", name: "Ice" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Fill a glass with ice.",
        ingredientIds: ["ice"],
      },
      {
        id: "s2",
        instruction: "Pour in the grape juice.",
        ingredientIds: ["grape"],
      },
      {
        id: "s3",
        instruction: "Top with sparkling water for bubbles!",
        ingredientIds: ["sparkle"],
      },
    ],
  },
  {
    id: "raspberry-iced-tea",
    title: "Raspberry Iced \"Tea\"",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Cold-brewed raspberry tea with honey — cool, fruity, and caffeine-free!",
    emoji: "🫖",
    placeholderColor: "#F8BBD0",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "drinks",
    baseServings: 1,
    imageSrc: "/recipes/raspberry-iced-tea.svg",
    ingredients: [
      { id: "water", name: "1 cup cold water" },
      { id: "tea", name: "1 decaf raspberry tea bag" },
      { id: "honey", name: "1 tsp honey" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Put the tea bag in the cold water and let it sit for 10 minutes.",
        timerSeconds: 600,
        timerLabel: "Steep tea",
        ingredientIds: ["water", "tea"],
      },
      {
        id: "s2",
        instruction: "Take the bag out and stir in the honey.",
        ingredientIds: ["honey"],
      },
      {
        id: "s3",
        instruction: "Add ice for a cool drink!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "peach-fizz",
    title: "Peach Fizz",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Peach juice mixed with lemon-lime soda — sweet, fuzzy, and fizzy!",
    emoji: "🍑",
    placeholderColor: "#FFAB91",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "drinks",
    baseServings: 1,
    imageSrc: "/recipes/peach-fizz.svg",
    ingredients: [
      { id: "peach", name: "1/2 cup peach juice" },
      { id: "soda", name: "1/2 cup lemon-lime soda" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Mix the juice and soda in a glass.",
        ingredientIds: ["peach", "soda"],
      },
      {
        id: "s2",
        instruction: "Sip your sweet peach fizz!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "fresh-strawberry-milk",
    title: "Fresh Strawberry Milk",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Real mashed strawberries stirred into cold milk — better than the carton!",
    emoji: "🍓",
    placeholderColor: "#F48FB1",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "drinks",
    baseServings: 1,
    imageSrc: "/recipes/fresh-strawberry-milk.svg",
    ingredients: [
      { id: "milk", name: "1 cup milk" },
      { id: "berries", name: "3 strawberries (mashed)" },
      { id: "sugar", name: "1 tsp sugar" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Mash the strawberries with the sugar until jammy.",
        ingredientIds: ["berries", "sugar"],
      },
      {
        id: "s2",
        instruction: "Stir the strawberry mix into the cold milk.",
        ingredientIds: ["milk"],
      },
      {
        id: "s3",
        instruction: "Drink your homemade strawberry milk!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "tropical-green-smoothie",
    title: "Tropical Green Smoothie",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Pineapple, banana, and spinach blend bright green — you can't taste the greens!",
    emoji: "🟢",
    placeholderColor: "#A5D6A7",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "drinks",
    baseServings: 1,
    imageSrc: "/recipes/tropical-green-smoothie.svg",
    ingredients: [
      { id: "juice", name: "1/2 cup pineapple juice" },
      { id: "spinach", name: "1/2 cup spinach" },
      { id: "banana", name: "1/2 banana" },
      { id: "ice", name: "Ice" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Put everything in the blender.",
        ingredientIds: ["juice", "spinach", "banana", "ice"],
      },
      {
        id: "s2",
        instruction: "Ask an adult to blend until bright green and smooth.",
        timerSeconds: 30,
        timerLabel: "Blend green",
        ingredientIds: [],
        needsAdult: true,
        adultReason: "Blenders need adult hands!",
      },
      {
        id: "s3",
        instruction: "Pour and taste the tropical surprise!",
        ingredientIds: [],
      },
    ],
  },
  {
    id: "warm-honey-vanilla-milk",
    title: "Warm Honey Vanilla Milk",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Warm milk with honey and vanilla — the coziest bedtime sip!",
    emoji: "🌙",
    placeholderColor: "#FFF8E1",
    pattern: "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)",
    suggestedCookbook: "drinks",
    baseServings: 1,
    imageSrc: "/recipes/warm-honey-vanilla-milk.svg",
    ingredients: [
      { id: "milk", name: "1 cup milk" },
      { id: "vanilla", name: "1/2 tsp vanilla" },
      { id: "honey", name: "1 tsp honey" },
    ],
    steps: [
      {
        id: "s1",
        instruction: "Mix everything in a mug.",
        ingredientIds: ["milk", "vanilla", "honey"],
      },
      {
        id: "s2",
        instruction: "Ask an adult to microwave for 1 minute until warm.",
        timerSeconds: 60,
        timerLabel: "Warm milk",
        ingredientIds: [],
        needsAdult: true,
        adultReason: "Hot drinks need adult help!",
      },
      {
        id: "s3",
        instruction: "Sip slowly before bedtime!",
        ingredientIds: [],
      },
    ],
  },
];
