/**
 * Generates lib/more-recipes-batch4.ts and SVG placeholders for batch 4 (100 recipes, IDs 176-275).
 * Run: node scripts/generate-batch4.js
 */
const fs = require("fs");
const path = require("path");

/** @typedef {{ id: string, name: string }} Ing */
/** @typedef {{ instruction: string, ingredientIds?: string[], needsAdult?: boolean, adultReason?: string, timerSeconds?: number, timerLabel?: string }} StepIn */

const recipes = [
  {
    id: "mini-breakfast-pizzas-bagel-thins",
    title: "Mini Breakfast Pizzas on Bagel Thins",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Crunchy bagel thins topped like tiny pizzas with cream cheese, cucumber, and tomato!",
    emoji: "🥯",
    color: "#FFE0B2",
    category: "breakfast",
    ingredients: [
      ["bagel", "1 bagel thin"],
      ["cream-cheese", "2 tbsp cream cheese"],
      ["cucumber", "4 slices of cucumber"],
      ["tomato", "1 cherry tomato (halved)"],
    ],
    steps: [
      ["Separate the bagel thin into two halves.", ["bagel"]],
      ["Spread cream cheese on each half.", ["cream-cheese"]],
      ["Place cucumber slices and tomato halves on top to make a face or a pattern.", ["cucumber","tomato"]],
      ["It's a crunchy, fresh way to start the day!", []],
    ],
  },
  {
    id: "pb-banana-sushi-crepes",
    title: "Peanut Butter & Banana Sushi Crepes",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "A peanut-butter crepe rolled around a banana and sliced into sushi-style rounds!",
    emoji: "🍌",
    color: "#FFF59D",
    category: "breakfast",
    ingredients: [
      ["pre-made", "1 pre-made crepe or thin pancake"],
      ["pb", "2 tbsp peanut butter"],
      ["banana", "1 banana"],
    ],
    steps: [
      ["Lay the crepe flat on a plate.", []],
      ["Spread peanut butter all over the crepe.", ["pre-made"]],
      ["Place the whole banana at one edge.", ["banana"]],
      ["Roll the crepe tightly around the banana.", ["banana"]],
      ["Ask an adult to slice the roll into \"sushi\" rounds.", [], {"needsAdult":true,"adultReason":"Cutting needs adult help!"}],
    ],
  },
  {
    id: "strawberry-cheesecake-breakfast-wraps",
    title: "Strawberry Cheesecake Breakfast Wraps",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Sweet cream cheese and strawberries wrapped up like breakfast cheesecake!",
    emoji: "🍓",
    color: "#F8BBD0",
    category: "breakfast",
    ingredients: [
      ["tortilla", "1 small flour tortilla"],
      ["cream-cheese", "2 tbsp cream cheese"],
      ["honey", "1 tsp honey"],
      ["strawberries", "3 strawberries (sliced)"],
    ],
    steps: [
      ["Mix the cream cheese and honey in a small bowl.", ["cream-cheese","honey"]],
      ["Spread the sweet cream cheese on the tortilla.", ["tortilla","cream-cheese"]],
      ["Place strawberry slices on top.", []],
      ["Fold it up and enjoy your breakfast \"dessert\"!", []],
    ],
  },
  {
    id: "microwave-scrambled-eggs-cup",
    title: "Microwave Scrambled Eggs in a Cup",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Fluffy scrambled eggs cooked in a mug — breakfast in under a minute!",
    emoji: "🍳",
    color: "#FFF9C4",
    category: "breakfast",
    ingredients: [
      ["eggs", "2 eggs"],
      ["milk", "1 tbsp milk"],
      ["salt", "a pinch of salt"],
      ["cheese", "1 tbsp shredded cheese"],
    ],
    steps: [
      ["Crack the eggs into a microwave-safe mug.", ["eggs"]],
      ["Add milk and salt, then whisk with a fork.", ["milk","salt"]],
      ["Ask an adult to microwave for 45 seconds, stir, then microwave for another 30-45 seconds until fluffy.", [], {"needsAdult":true,"adultReason":"Hot microwave!","timerSeconds":90,"timerLabel":"Microwave eggs"}],
      ["Sprinkle cheese on top and let it melt.", ["cheese"]],
    ],
  },
  {
    id: "apple-almond-butter-donuts",
    title: "Apple & Almond Butter \"Donuts\"",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Apple rings spread with almond butter and granola — healthy donuts you can build!",
    emoji: "🍎",
    color: "#FFCC80",
    category: "breakfast",
    ingredients: [
      ["apple", "1 apple"],
      ["almond-butter", "2 tbsp almond butter"],
      ["granola", "1 tbsp granola"],
    ],
    steps: [
      ["Ask an adult to slice the apple into thick rings and remove the core.", ["apple"], {"needsAdult":true,"adultReason":"Cutting needs adult help!"}],
      ["Spread almond butter on one side of each ring.", ["almond-butter"]],
      ["Sprinkle granola on top for a healthy \"donut\" crunch!", ["granola"]],
    ],
  },
  {
    id: "blueberry-yogurt-breakfast-bark",
    title: "Blueberry & Yogurt Breakfast Bark",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Tangy yogurt bark studded with blueberries — break it into breakfast shards!",
    emoji: "🫐",
    color: "#CE93D8",
    category: "breakfast",
    ingredients: [
      ["greek-yogurt", "1 cup Greek yogurt"],
      ["blueberries", "1/2 cup blueberries"],
      ["maple", "1 tsp maple syrup"],
    ],
    steps: [
      ["Mix the yogurt and maple syrup.", ["greek-yogurt","maple"]],
      ["Spread the yogurt in a thin layer on a tray with wax paper.", ["greek-yogurt"]],
      ["Drop blueberries all over the top.", ["blueberries"]],
      ["Freeze until hard, then break into big pieces.", [], {"timerSeconds":10800,"timerLabel":"Freeze"}],
    ],
  },
  {
    id: "breakfast-fruit-kabobs-honey-dip",
    title: "Breakfast Fruit Kabobs with Honey Dip",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Colorful fruit wands dunked in honey-sweet yogurt dip!",
    emoji: "🍢",
    color: "#A5D6A7",
    category: "breakfast",
    ingredients: [
      ["melon-chunks", "Melon chunks"],
      ["pineapple", "pineapple"],
      ["strawberries", "strawberries"],
      ["yogurt", "1/2 cup yogurt"],
      ["honey", "1 tsp honey"],
    ],
    steps: [
      ["Slide the fruit pieces onto wooden skewers.", []],
      ["In a small bowl, mix the yogurt and honey.", ["yogurt","honey"]],
      ["Dip your fruit wands into the sweet yogurt.", ["yogurt"]],
    ],
  },
  {
    id: "overnight-peach-vanilla-oats",
    title: "Overnight Peach & Vanilla Oats",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Peachy vanilla oats that chill overnight so breakfast is ready when you wake up!",
    emoji: "🍑",
    color: "#FFCCBC",
    category: "breakfast",
    ingredients: [
      ["oats", "1/2 cup oats"],
      ["milk", "1/2 cup milk"],
      ["peach", "1/2 peach (chopped)"],
      ["vanilla", "1/4 tsp vanilla"],
    ],
    steps: [
      ["Put all ingredients into a jar and stir well.", []],
      ["Put the lid on and keep it in the fridge overnight.", [], {"timerSeconds":28800,"timerLabel":"Chill overnight"}],
      ["In the morning, stir it up and eat it cold!", []],
    ],
  },
  {
    id: "breakfast-egg-muffins-ham",
    title: "Breakfast Egg Muffins with Ham",
    cookTimeMins: 20,
    safety: "adult-helper",
    description: "Mini egg muffins packed with ham and cheese — grab-and-go protein cups!",
    emoji: "🧁",
    color: "#EF9A9A",
    category: "breakfast",
    ingredients: [
      ["eggs", "4 eggs"],
      ["ham", "2 slices of ham (chopped)"],
      ["cheese", "1/4 cup shredded cheese"],
    ],
    steps: [
      ["Whisk the eggs in a bowl.", ["eggs"]],
      ["Stir in the ham and cheese.", ["ham","cheese"]],
      ["Ask an adult to pour the mix into a greased muffin tin.", [], {"needsAdult":true,"adultReason":"Ask an adult for help with this step!"}],
      ["Ask an adult to bake at 350°F for 15 minutes until firm.", [], {"needsAdult":true,"adultReason":"Hot oven!","timerSeconds":900,"timerLabel":"Bake"}],
    ],
  },
  {
    id: "banana-walnut-breakfast-cookies",
    title: "Banana & Walnut Breakfast Cookies",
    cookTimeMins: 15,
    safety: "adult-helper",
    description: "Soft banana-oat cookies with crunchy walnuts — cookies for breakfast!",
    emoji: "🍪",
    color: "#D7CCC8",
    category: "breakfast",
    ingredients: [
      ["banana", "1 ripe banana"],
      ["oats", "1 cup oats"],
      ["walnuts", "2 tbsp chopped walnuts"],
    ],
    steps: [
      ["Mash the banana in a bowl.", ["banana"]],
      ["Stir in the oats and walnuts.", ["oats","walnuts"]],
      ["Put spoonfuls on a baking tray.", []],
      ["Ask an adult to bake at 350°F for 10-12 minutes.", [], {"needsAdult":true,"adultReason":"Hot oven!","timerSeconds":660,"timerLabel":"Bake"}],
    ],
  },
  {
    id: "cottage-cheese-pineapple-boats",
    title: "Cottage Cheese & Pineapple Boats",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Creamy cottage cheese topped with pineapple and sunflower seeds!",
    emoji: "🍍",
    color: "#FFF59D",
    category: "breakfast",
    ingredients: [
      ["cottage-cheese", "1/2 cup cottage cheese"],
      ["pineapple", "2 pineapple slices"],
      ["seeds", "1 tbsp sunflower seeds"],
    ],
    steps: [
      ["Put the cottage cheese in a bowl.", ["cottage-cheese"]],
      ["Top with pineapple slices.", ["pineapple"]],
      ["Sprinkle seeds on top for a little crunch.", ["seeds"]],
    ],
  },
  {
    id: "cereal-yogurt-breakfast-parfait-raspberries",
    title: "Cereal & Yogurt Breakfast Parfait",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Layers of yogurt, crispy cereal, and raspberries — crunch before it softens!",
    emoji: "🥣",
    color: "#B3E5FC",
    category: "breakfast",
    ingredients: [
      ["yogurt", "1/2 cup yogurt"],
      ["crispy-rice", "1/2 cup crispy rice cereal"],
      ["raspberries", "1/4 cup raspberries"],
    ],
    steps: [
      ["Layer yogurt, cereal, and berries in a glass.", ["yogurt"]],
      ["Repeat the layers until the glass is full.", []],
      ["Eat it quickly so the cereal stays crunchy!", []],
    ],
  },
  {
    id: "toasted-english-muffin-ricotta-berries",
    title: "Toasted English Muffin with Ricotta & Berries",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Toasty English muffin with fluffy ricotta and juicy blueberries!",
    emoji: "🫐",
    color: "#E1BEE7",
    category: "breakfast",
    ingredients: [
      ["muffin", "1 English muffin"],
      ["ricotta-cheese", "2 tbsp ricotta cheese"],
      ["blueberries", "1/4 cup blueberries"],
    ],
    steps: [
      ["Ask an adult to toast the English muffin.", ["muffin"], {"needsAdult":true,"adultReason":"Toasters need adult help!"}],
      ["Spread ricotta on each half.", ["ricotta-cheese"]],
      ["Top with blueberries and a tiny drizzle of honey if you like.", ["blueberries"]],
    ],
  },
  {
    id: "breakfast-apple-nachos-granola",
    title: "Breakfast Apple \"Nachos\" with Granola",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Apple-slice nachos with peanut butter, yogurt drizzle, and granola crunch!",
    emoji: "🍎",
    color: "#FFCC80",
    category: "breakfast",
    ingredients: [
      ["apple", "1 apple (sliced)"],
      ["pb", "1 tbsp peanut butter"],
      ["yogurt", "1 tbsp yogurt"],
      ["granola", "1 tbsp granola"],
    ],
    steps: [
      ["Arrange apple slices on a plate.", ["apple"]],
      ["Drizzle peanut butter and yogurt over them.", ["yogurt"]],
      ["Sprinkle granola on top.", ["granola"]],
    ],
  },
  {
    id: "mini-pancake-fruit-skewers-v2",
    title: "Mini Pancake & Fruit Skewers",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Mini pancakes and fruit stacked on sticks — breakfast you can wave around!",
    emoji: "🥞",
    color: "#FFE082",
    category: "breakfast",
    ingredients: [
      ["pancakes", "6 mini pancakes"],
      ["strawberries", "6 strawberries"],
      ["grapes", "6 grapes"],
    ],
    steps: [
      ["Ask an adult to warm the mini pancakes.", ["pancakes"], {"needsAdult":true,"adultReason":"Hot stove!"}],
      ["Thread a pancake, then a strawberry, then another pancake, then a grape onto a skewer.", []],
      ["It's breakfast on a stick!", []],
    ],
  },
  {
    id: "simple-cheese-chive-scones",
    title: "Simple Cheese & Chive Scones",
    cookTimeMins: 20,
    safety: "adult-helper",
    description: "Cheesy chive scones that bake up soft and savory!",
    emoji: "🧀",
    color: "#FFF8E1",
    category: "breakfast",
    ingredients: [
      ["flour", "1 cup self-rising flour"],
      ["cheese", "1/2 cup shredded cheese"],
      ["chives", "1 tbsp chopped chives"],
      ["milk", "1/2 cup milk"],
    ],
    steps: [
      ["Mix flour, cheese, and chives in a bowl.", ["flour","cheese","chives"]],
      ["Add milk and stir until it makes a dough.", ["milk"]],
      ["Put spoonfuls on a baking tray.", []],
      ["Ask an adult to bake at 400°F for 12 minutes.", [], {"needsAdult":true,"adultReason":"Hot oven!","timerSeconds":720,"timerLabel":"Bake"}],
    ],
  },
  {
    id: "breakfast-taco-scrambled-eggs",
    title: "Breakfast Taco with Scrambled Eggs",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "A warm tortilla taco filled with scrambled eggs, cheese, and salsa!",
    emoji: "🌮",
    color: "#FFCCBC",
    category: "breakfast",
    ingredients: [
      ["tortilla", "1 small tortilla"],
      ["scrambled-egg", "1 scrambled egg"],
      ["cheese", "2 tbsp shredded cheese"],
      ["salsa", "1 tbsp salsa"],
    ],
    steps: [
      ["Put the warm scrambled egg in the tortilla.", ["tortilla","scrambled-egg"]],
      ["Sprinkle cheese and salsa on top.", ["cheese","salsa"]],
      ["Fold it up and eat it like a taco.", []],
    ],
  },
  {
    id: "nutella-banana-toast-chia",
    title: "Nutella & Banana Toast with Chia Seeds",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Toast with Nutella, banana coins, and a sprinkle of chia seeds!",
    emoji: "🍞",
    color: "#D7CCC8",
    category: "breakfast",
    ingredients: [
      ["bread", "1 slice of bread"],
      ["nutella", "1 tbsp Nutella"],
      ["banana", "1/2 banana (sliced)"],
      ["chia", "1 tsp chia seeds"],
    ],
    steps: [
      ["Ask an adult to toast the bread.", ["bread"], {"needsAdult":true,"adultReason":"Toasters need adult help!"}],
      ["Spread Nutella on top.", ["nutella"]],
      ["Add banana slices and sprinkle with chia seeds.", ["banana","chia"]],
    ],
  },
  {
    id: "hard-boiled-egg-sailboats-v2",
    title: "Hard Boiled Egg \"Sailboats\"",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Hard-boiled egg boats sailing with cheese-triangle sails!",
    emoji: "⛵",
    color: "#FFF59D",
    category: "breakfast",
    ingredients: [
      ["egg", "1 hard-boiled egg"],
      ["cheese", "1 slice of cheese"],
      ["toothpick", "1 toothpick"],
    ],
    steps: [
      ["Ask an adult to cut the egg in half.", ["egg"], {"needsAdult":true,"adultReason":"Cutting needs adult help!"}],
      ["Cut the cheese into a triangle.", ["cheese"]],
      ["Poke the toothpick through the cheese and into the egg to make a sail.", ["egg","cheese","toothpick"]],
    ],
  },
  {
    id: "breakfast-quesadilla-cheese-ham",
    title: "Breakfast Quesadilla with Cheese & Ham",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "A folded tortilla quesadilla stuffed with ham and melty cheese!",
    emoji: "🫓",
    color: "#FFE0B2",
    category: "breakfast",
    ingredients: [
      ["tortilla", "1 tortilla"],
      ["cheese", "1/4 cup cheese"],
      ["ham", "1 slice of ham (chopped)"],
    ],
    steps: [
      ["Put cheese and ham on half of the tortilla.", ["tortilla","cheese","ham"]],
      ["Fold it in half.", []],
      ["Ask an adult to warm it in a pan until the cheese melts.", ["cheese"], {"needsAdult":true,"adultReason":"Hot stove!"}],
    ],
  },
  {
    id: "granola-yogurt-bark-strawberries",
    title: "Granola & Yogurt Bark with Strawberries",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Yogurt bark topped with granola and strawberries — freeze and snap!",
    emoji: "🍓",
    color: "#F8BBD0",
    category: "breakfast",
    ingredients: [
      ["yogurt", "1 cup yogurt"],
      ["granola", "1/4 cup granola"],
      ["strawberries", "3 strawberries (sliced)"],
    ],
    steps: [
      ["Spread yogurt on a tray.", ["yogurt"]],
      ["Sprinkle granola and strawberry slices on top.", ["granola"]],
      ["Freeze until hard, then break into pieces.", [], {"timerSeconds":7200,"timerLabel":"Freeze"}],
    ],
  },
  {
    id: "pumpkin-spice-overnight-chia-pudding",
    title: "Pumpkin Spice Overnight Chia Pudding",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Pumpkin-spiced chia pudding that sets overnight into a cozy jar treat!",
    emoji: "🎃",
    color: "#FFCC80",
    category: "breakfast",
    ingredients: [
      ["milk", "1/2 cup milk"],
      ["chia", "2 tbsp chia seeds"],
      ["pumpkin", "1 tbsp pumpkin puree"],
      ["cinnamon", "a pinch of cinnamon"],
    ],
    steps: [
      ["Mix everything in a jar and stir well.", []],
      ["Put the lid on and leave it in the fridge overnight.", [], {"timerSeconds":28800,"timerLabel":"Chill overnight"}],
      ["Stir it up in the morning for a pumpkin treat!", ["pumpkin"]],
    ],
  },
  {
    id: "breakfast-sliders-egg-cheese",
    title: "Breakfast Sliders with Egg & Cheese",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Mini rolls stuffed with scrambled egg and cheese — breakfast on the go!",
    emoji: "🍔",
    color: "#FFE082",
    category: "breakfast",
    ingredients: [
      ["item", "2 mini rolls"],
      ["scrambled-egg", "1 scrambled egg"],
      ["cheese", "1 slice of cheese"],
    ],
    steps: [
      ["Cut the rolls in half.", []],
      ["Put egg and a piece of cheese in each roll.", ["scrambled-egg","cheese"]],
      ["These are great for breakfast on the go!", []],
    ],
  },
  {
    id: "peach-almond-yogurt-bowl-honey",
    title: "Peach & Almond Yogurt Bowl with Honey",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "A sunny yogurt bowl with peaches, almonds, and a honey drizzle!",
    emoji: "🍑",
    color: "#FFCCBC",
    category: "breakfast",
    ingredients: [
      ["yogurt", "1/2 cup yogurt"],
      ["peach", "1/2 peach (sliced)"],
      ["almonds", "1 tbsp sliced almonds"],
      ["honey", "1 tsp honey"],
    ],
    steps: [
      ["Put yogurt in a bowl.", ["yogurt"]],
      ["Top with peach slices and almonds.", ["peach","almonds"]],
      ["Drizzle with honey.", ["honey"]],
    ],
  },
  {
    id: "ricotta-honey-toast-sliced-pears",
    title: "Ricotta & Honey Toast with Sliced Pears",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Toast with creamy ricotta, pear slices, and sweet honey!",
    emoji: "🍐",
    color: "#FFF8E1",
    category: "breakfast",
    ingredients: [
      ["bread", "1 slice of bread"],
      ["ricotta", "2 tbsp ricotta"],
      ["pear", "1/2 pear (sliced)"],
      ["honey", "1 tsp honey"],
    ],
    steps: [
      ["Ask an adult to toast the bread.", ["bread"], {"needsAdult":true,"adultReason":"Toasters need adult help!"}],
      ["Spread ricotta on top.", ["ricotta"]],
      ["Add pear slices and drizzle with honey. Dinner & Lunch.", ["pear","honey"]],
    ],
  },
  {
    id: "mini-meatball-subs-dinner-rolls",
    title: "Mini Meatball Subs on Dinner Rolls",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Dinner rolls stuffed with meatballs, sauce, and melty cheese!",
    emoji: "🥖",
    color: "#EF9A9A",
    category: "dinner",
    ingredients: [
      ["dinner", "2 dinner rolls"],
      ["meatballs", "4 frozen meatballs (thawed)"],
      ["sauce", "2 tbsp pasta sauce"],
      ["cheese", "2 tbsp shredded cheese"],
    ],
    steps: [
      ["Cut a small hole in the top of each roll.", []],
      ["Put two meatballs and some sauce inside each roll.", ["meatballs","sauce"]],
      ["Sprinkle with cheese.", ["cheese"]],
      ["Ask an adult to microwave for 30 seconds to melt the cheese.", ["cheese"], {"needsAdult":true,"adultReason":"Hot microwave!","timerSeconds":30,"timerLabel":"Microwave"}],
    ],
  },
  {
    id: "crescent-pizza-pockets-pepperoni",
    title: "Crescent Roll Pizza Pockets with Pepperoni",
    cookTimeMins: 15,
    safety: "adult-helper",
    description: "Pepperoni and cheese tucked into golden crescent pizza pockets!",
    emoji: "🍕",
    color: "#FFCC80",
    category: "dinner",
    ingredients: [
      ["dough", "1 can crescent roll dough"],
      ["pepperoni", "4 pepperoni slices"],
      ["cheese", "2 cheese sticks"],
    ],
    steps: [
      ["Unroll the dough into triangles.", ["dough"]],
      ["Put a pepperoni and half a cheese stick on the wide end.", ["pepperoni","cheese"]],
      ["Roll it up and pinch the sides.", []],
      ["Ask an adult to bake at 375°F for 10-12 minutes.", [], {"needsAdult":true,"adultReason":"Hot oven!","timerSeconds":660,"timerLabel":"Bake"}],
    ],
  },
  {
    id: "sloppy-joe-sliders-mini-buns",
    title: "Sloppy Joe Sliders on Mini Buns",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Messy, saucy sloppy joe meat piled on mini buns!",
    emoji: "🍔",
    color: "#FFAB91",
    category: "dinner",
    ingredients: [
      ["buns", "2 mini buns"],
      ["pre-sloppy", "1/2 cup pre-cooked sloppy joe meat"],
      ["cheese", "1 slice of cheese"],
    ],
    steps: [
      ["Spoon the warm meat onto the buns.", ["buns"]],
      ["Add a piece of cheese and put the top bun on.", ["cheese"]],
      ["They are messy but so good!", []],
    ],
  },
  {
    id: "baked-potato-bar-cheese-sour-cream",
    title: "Baked Potato Bar with Cheese & Sour Cream",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "A fluffy baked potato loaded with cheese and sour cream!",
    emoji: "🥔",
    color: "#D7CCC8",
    category: "dinner",
    ingredients: [
      ["baked-potato", "1 baked potato (pre-cooked)"],
      ["cheese", "2 tbsp cheese"],
      ["sour-cream", "1 tbsp sour cream"],
    ],
    steps: [
      ["Ask an adult to cut a slit in the warm potato.", ["baked-potato"], {"needsAdult":true,"adultReason":"Cutting needs adult help!"}],
      ["Fluff the inside with a fork.", []],
      ["Add your cheese and sour cream.", ["cheese","sour-cream"]],
    ],
  },
  {
    id: "chicken-nugget-tacos-ranch",
    title: "Chicken Nugget Tacos with Ranch",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Crispy nugget tacos topped with lettuce and ranch!",
    emoji: "🌮",
    color: "#FFE082",
    category: "dinner",
    ingredients: [
      ["tortillas", "2 small tortillas"],
      ["nuggets", "4 cooked chicken nuggets"],
      ["lettuce", "1/4 cup shredded lettuce"],
      ["ranch", "1 tbsp ranch dressing"],
    ],
    steps: [
      ["Put two nuggets in each tortilla.", ["nuggets"]],
      ["Top with lettuce and drizzle with ranch.", ["lettuce","ranch"]],
    ],
  },
  {
    id: "simple-veggie-ramen-peas-carrots",
    title: "Simple Veggie Ramen with Peas & Carrots",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Ramen noodles with peas and carrots — a quick cozy bowl!",
    emoji: "🍜",
    color: "#A5D6A7",
    category: "dinner",
    ingredients: [
      ["ramen-noodles", "1 pack ramen noodles"],
      ["peas-carrots", "1/4 cup frozen peas and carrots"],
    ],
    steps: [
      ["Ask an adult to cook the noodles and veggies in boiling water.", ["ramen-noodles"], {"needsAdult":true,"adultReason":"Hot stove!"}],
      ["Drain most of the water and stir in the flavor packet.", []],
    ],
  },
  {
    id: "pesto-pasta-green-peas",
    title: "Pesto Pasta with Green Peas",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Warm pasta swirled with pesto and bright green peas!",
    emoji: "🍝",
    color: "#C5E1A5",
    category: "dinner",
    ingredients: [
      ["pasta", "1 cup cooked pasta"],
      ["pesto-sauce", "1 tbsp pesto sauce"],
      ["peas", "2 tbsp peas"],
    ],
    steps: [
      ["Mix the warm pasta with pesto sauce.", ["pasta","pesto-sauce"]],
      ["Stir in the peas for a bright green meal.", ["peas"]],
    ],
  },
  {
    id: "fish-stick-tacos-cabbage-slaw",
    title: "Fish Stick Tacos with Cabbage Slaw",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Crunchy fish-stick tacos topped with cabbage and a dab of mayo!",
    emoji: "🐟",
    color: "#81D4FA",
    category: "dinner",
    ingredients: [
      ["tortillas", "2 small tortillas"],
      ["fish", "4 cooked fish sticks"],
      ["cabbage", "1/4 cup shredded cabbage"],
      ["mayo", "1 tsp mayo"],
    ],
    steps: [
      ["Place fish sticks in the tortillas.", ["tortillas","fish"]],
      ["Top with cabbage and a dot of mayo.", ["cabbage","mayo"]],
    ],
  },
  {
    id: "mini-shepherds-pies-corn-potatoes",
    title: "Mini Shepherd's Pies with Corn & Potatoes",
    cookTimeMins: 15,
    safety: "adult-helper",
    description: "Tiny shepherd's pies with corn and mashed potato tops!",
    emoji: "🥧",
    color: "#BCAAA4",
    category: "dinner",
    ingredients: [
      ["beef", "1/2 cup cooked ground beef"],
      ["potatoes", "1/2 cup mashed potatoes"],
      ["corn", "2 tbsp corn"],
    ],
    steps: [
      ["Put the beef in a small bowl.", ["beef"]],
      ["Add a layer of corn and top with mashed potatoes.", ["potatoes","corn"]],
      ["Ask an adult to bake at 350°F for 10 minutes.", [], {"needsAdult":true,"adultReason":"Hot oven!","timerSeconds":600,"timerLabel":"Bake"}],
    ],
  },
  {
    id: "taco-cupcakes-wonton-wrappers",
    title: "Taco Cupcakes with Wonton Wrappers",
    cookTimeMins: 15,
    safety: "adult-helper",
    description: "Wonton cups baked into taco cupcakes with cheesy beef filling!",
    emoji: "🧁",
    color: "#FFCC80",
    category: "dinner",
    ingredients: [
      ["wonton", "4 wonton wrappers"],
      ["meat", "1/2 cup taco meat"],
      ["cheese", "1/4 cup cheese"],
    ],
    steps: [
      ["Ask an adult to press wrappers into a muffin tin.", [], {"needsAdult":true,"adultReason":"Ask an adult for help with this step!"}],
      ["Fill with meat and cheese.", ["meat","cheese"]],
      ["Ask an adult to bake at 375°F for 10 minutes.", [], {"needsAdult":true,"adultReason":"Hot oven!","timerSeconds":600,"timerLabel":"Bake"}],
    ],
  },
  {
    id: "spaghetti-meatball-skewers-dipping",
    title: "Spaghetti & Meatball Skewers for Dipping",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Spaghetti-wrapped meatballs on sticks for dunking in sauce!",
    emoji: "🍢",
    color: "#EF9A9A",
    category: "dinner",
    ingredients: [
      ["meatballs", "4 cooked meatballs"],
      ["pasta", "1/2 cup cooked thick pasta"],
      ["sauce", "1/4 cup pasta sauce"],
    ],
    steps: [
      ["Thread a meatball and then a piece of pasta onto a skewer.", ["pasta"]],
      ["Dip the skewer into the warm sauce.", ["sauce"]],
    ],
  },
  {
    id: "grilled-cheese-roll-ups-dipping",
    title: "Grilled Cheese Roll-ups with Dipping Sauce",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Rolled grilled cheese sticks perfect for tomato-soup dipping!",
    emoji: "🧀",
    color: "#FFE082",
    category: "dinner",
    ingredients: [
      ["bread", "1 slice of bread (crusts removed)"],
      ["cheese", "1 slice of cheese"],
      ["butter", "1 tsp butter"],
    ],
    steps: [
      ["Flatten the bread and put the cheese on top.", ["bread","cheese"]],
      ["Roll it up tight.", []],
      ["Ask an adult to cook in a pan with butter until golden.", ["butter"], {"needsAdult":true,"adultReason":"Hot stove!"}],
    ],
  },
  {
    id: "pizza-quesadillas-pepperoni-sauce",
    title: "Pizza Quesadillas with Pepperoni & Sauce",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Pepperoni pizza flavors melted inside a crispy quesadilla!",
    emoji: "🍕",
    color: "#FFAB91",
    category: "dinner",
    ingredients: [
      ["tortilla", "1 tortilla"],
      ["cheese", "1/4 cup cheese"],
      ["pepperoni", "4 pepperoni slices"],
      ["sauce", "1 tbsp pizza sauce"],
    ],
    steps: [
      ["Spread sauce on half the tortilla.", ["tortilla","sauce"]],
      ["Add cheese and pepperoni, then fold.", ["cheese","pepperoni"]],
      ["Ask an adult to warm in a pan until melty.", [], {"needsAdult":true,"adultReason":"Hot stove!"}],
    ],
  },
  {
    id: "hot-dog-mummies-crescent-dough",
    title: "Hot Dog Mummies with Crescent Dough",
    cookTimeMins: 15,
    safety: "adult-helper",
    description: "Hot dogs wrapped like crescent-dough mummies — spooky and delicious!",
    emoji: "🌭",
    color: "#FFCCBC",
    category: "dinner",
    ingredients: [
      ["dogs", "2 hot dogs"],
      ["dough", "1 can crescent dough"],
    ],
    steps: [
      ["Wrap thin strips of dough around the hot dog like a mummy.", ["dough"]],
      ["Ask an adult to bake at 375°F for 10-12 minutes.", [], {"needsAdult":true,"adultReason":"Hot oven!","timerSeconds":660,"timerLabel":"Bake"}],
    ],
  },
  {
    id: "chicken-broccoli-sheet-pan-dinner",
    title: "Chicken & Broccoli Sheet Pan Dinner",
    cookTimeMins: 20,
    safety: "adult-helper",
    description: "Chicken and broccoli roasted together on one sheet pan!",
    emoji: "🥦",
    color: "#C5E1A5",
    category: "dinner",
    ingredients: [
      ["chicken", "1/2 cup cooked chicken"],
      ["broccoli", "1/2 cup broccoli"],
      ["oil", "1 tsp olive oil"],
    ],
    steps: [
      ["Put chicken and broccoli on a baking sheet.", ["chicken","broccoli"]],
      ["Drizzle with oil and a pinch of salt.", ["oil"]],
      ["Ask an adult to bake at 400°F for 15 minutes.", [], {"needsAdult":true,"adultReason":"Hot oven!","timerSeconds":900,"timerLabel":"Bake"}],
    ],
  },
  {
    id: "mini-calzones-biscuit-dough",
    title: "Mini Calzones with Biscuit Dough",
    cookTimeMins: 15,
    safety: "adult-helper",
    description: "Mini biscuit-dough calzones stuffed with pizza fillings!",
    emoji: "🥟",
    color: "#D7CCC8",
    category: "dinner",
    ingredients: [
      ["biscuit", "1 refrigerated biscuit"],
      ["sauce", "1 tbsp sauce"],
      ["cheese", "1 tbsp cheese"],
    ],
    steps: [
      ["Flatten the biscuit and put sauce and cheese in the middle.", ["biscuit","sauce","cheese"]],
      ["Fold and pinch the edges.", []],
      ["Ask an adult to bake at 375°F for 10 minutes.", [], {"needsAdult":true,"adultReason":"Hot oven!","timerSeconds":600,"timerLabel":"Bake"}],
    ],
  },
  {
    id: "bbq-chicken-flatbread-pizza",
    title: "BBQ Chicken Flatbread Pizza",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Flatbread pizza with BBQ chicken and melty cheese!",
    emoji: "🍕",
    color: "#FFAB91",
    category: "dinner",
    ingredients: [
      ["flatbread", "1 flatbread"],
      ["bbq", "2 tbsp BBQ sauce"],
      ["chicken", "1/4 cup cooked chicken"],
      ["cheese", "1/4 cup cheese"],
    ],
    steps: [
      ["Spread BBQ sauce on the flatbread.", ["flatbread","bbq"]],
      ["Add chicken and cheese.", ["chicken","cheese"]],
      ["Ask an adult to bake at 350°F for 8 minutes.", [], {"needsAdult":true,"adultReason":"Hot oven!","timerSeconds":480,"timerLabel":"Bake"}],
    ],
  },
  {
    id: "mac-cheese-broccoli-trees-v2",
    title: "Mac & Cheese with Broccoli \"Trees\"",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Creamy mac and cheese with broccoli trees standing tall!",
    emoji: "🧀",
    color: "#FFF59D",
    category: "dinner",
    ingredients: [
      ["mac", "1 bowl mac & cheese"],
      ["broccoli", "4 small broccoli florets"],
    ],
    steps: [
      ["Make your mac & cheese.", ["mac"]],
      ["Poke the broccoli into the cheese so they look like trees.", ["broccoli"]],
    ],
  },
  {
    id: "turkey-apple-sandwiches-whole-wheat",
    title: "Turkey & Apple Sandwiches on Whole Wheat",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Turkey and crisp apple on whole wheat — sweet and savory!",
    emoji: "🥪",
    color: "#A5D6A7",
    category: "dinner",
    ingredients: [
      ["bread", "2 slices of bread"],
      ["turkey", "2 slices of turkey"],
      ["apple", "4 thin apple slices"],
    ],
    steps: [
      ["Put turkey and apple slices on the bread.", ["bread","turkey","apple"]],
      ["Close the sandwich and enjoy the crunch!", []],
    ],
  },
  {
    id: "bean-cheese-tostadas-salsa",
    title: "Bean & Cheese Tostadas with Salsa",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Crunchy tostadas piled with beans, cheese, and salsa!",
    emoji: "🌮",
    color: "#FFCC80",
    category: "dinner",
    ingredients: [
      ["tostada", "1 tostada shell"],
      ["beans", "2 tbsp refried beans"],
      ["cheese", "2 tbsp cheese"],
    ],
    steps: [
      ["Spread beans on the shell and sprinkle with cheese.", ["beans","cheese"]],
      ["Ask an adult to warm in the microwave for 20 seconds.", [], {"needsAdult":true,"adultReason":"Hot microwave!","timerSeconds":20,"timerLabel":"Microwave"}],
    ],
  },
  {
    id: "mini-bagel-pizzas-veggie-toppings",
    title: "Mini Bagel Pizzas with Veggie Toppings",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Mini bagel pizzas topped with sauce, cheese, and veggies!",
    emoji: "🥯",
    color: "#FFAB91",
    category: "dinner",
    ingredients: [
      ["bagel", "1 mini bagel"],
      ["sauce", "2 tbsp sauce"],
      ["cheese", "2 tbsp cheese"],
      ["peppers", "1 tbsp chopped peppers"],
    ],
    steps: [
      ["Put sauce, cheese, and peppers on the bagel halves.", ["bagel","sauce","cheese","peppers"]],
      ["Ask an adult to bake or toast until bubbly.", [], {"needsAdult":true,"adultReason":"Hot oven!","timerSeconds":480,"timerLabel":"Bake pizzas"}],
    ],
  },
  {
    id: "ham-cheese-crescent-squares-v2",
    title: "Ham & Cheese Crescent Squares",
    cookTimeMins: 15,
    safety: "adult-helper",
    description: "Ham and cheese baked in flaky crescent squares!",
    emoji: "🥐",
    color: "#FFCCBC",
    category: "dinner",
    ingredients: [
      ["dough", "1 crescent roll dough"],
      ["ham", "2 slices of ham"],
      ["cheese", "1 slice of cheese"],
    ],
    steps: [
      ["Put ham and cheese in the middle of a dough square.", ["dough","ham","cheese"]],
      ["Fold the corners over.", []],
      ["Ask an adult to bake at 375°F for 10 minutes.", [], {"needsAdult":true,"adultReason":"Hot oven!","timerSeconds":600,"timerLabel":"Bake"}],
    ],
  },
  {
    id: "cold-soba-noodle-salad-cucumber",
    title: "Cold Soba Noodle Salad with Cucumber",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Cool soba noodles with cucumber — a refreshing noodle salad!",
    emoji: "🥒",
    color: "#C5E1A5",
    category: "dinner",
    ingredients: [
      ["noodles", "1 cup cold noodles"],
      ["soy", "1 tbsp soy sauce"],
      ["honey", "1 tsp honey"],
      ["cucumber", "cucumber slices"],
    ],
    steps: [
      ["Mix soy sauce and honey with the noodles.", ["noodles","soy","honey"]],
      ["Add cucumber slices and stir.", ["cucumber"]],
    ],
  },
  {
    id: "pizza-bagels-extra-cheese",
    title: "Pizza Bagels with Extra Cheese",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Classic pizza bagels loaded with extra cheese!",
    emoji: "🍕",
    color: "#EF9A9A",
    category: "dinner",
    ingredients: [
      ["bagel", "1 large bagel"],
      ["sauce", "1/4 cup sauce"],
      ["cheese", "1/4 cup cheese"],
    ],
    steps: [
      ["Put sauce and lots of cheese on the bagel halves.", ["bagel","sauce","cheese"]],
      ["Ask an adult to bake at 350°F for 10 minutes.", [], {"needsAdult":true,"adultReason":"Hot oven!","timerSeconds":600,"timerLabel":"Bake"}],
    ],
  },
  {
    id: "ants-on-a-raft-tuna-crackers",
    title: "\"Ants on a Raft\" Tuna Crackers",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Tuna crackers with raisin ants floating on mayo rafts!",
    emoji: "🐜",
    color: "#D7CCC8",
    category: "dinner",
    ingredients: [
      ["crackers", "4 square crackers"],
      ["tuna", "1/4 cup tuna salad"],
      ["raisins", "8 raisins"],
    ],
    steps: [
      ["Spread tuna salad on the crackers.", ["crackers","tuna"]],
      ["Put two raisins on each cracker as the \"ants.\" Dessert & Snacks.", ["raisins"]],
    ],
  },
  {
    id: "no-bake-oreo-truffles-cream-cheese",
    title: "No-Bake Oreo Truffles with Cream Cheese",
    cookTimeMins: 15,
    safety: "kid-solo",
    description: "Crushed Oreos mixed with cream cheese rolled into no-bake truffles!",
    emoji: "🍪",
    color: "#4E342E",
    category: "dessert",
    ingredients: [
      ["oreos", "10 Oreo cookies"],
      ["cream-cheese", "2 tbsp cream cheese"],
      ["chocolate", "1/4 cup melted chocolate"],
    ],
    steps: [
      ["Crush the cookies and mix with cream cheese.", ["cream-cheese"]],
      ["Roll into balls and dip in melted chocolate.", ["chocolate"]],
      ["Chill in the fridge until firm.", [], {"timerSeconds":1800,"timerLabel":"Chill truffles"}],
    ],
  },
  {
    id: "cookie-mug-cake-chocolate-chips",
    title: "Cookie Mug Cake with Chocolate Chips",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "A gooey chocolate-chip cookie cake baked in a mug!",
    emoji: "☕",
    color: "#D7CCC8",
    category: "dessert",
    ingredients: [
      ["butter", "1 tbsp butter"],
      ["sugar", "1 tbsp sugar"],
      ["brown-sugar", "1 tbsp brown sugar"],
      ["flour", "3 tbsp flour"],
      ["chips", "1 tbsp chocolate chips"],
    ],
    steps: [
      ["Mix everything in a mug.", []],
      ["Ask an adult to microwave for 45-60 seconds.", [], {"needsAdult":true,"adultReason":"Hot microwave!","timerSeconds":90,"timerLabel":"Microwave eggs"}],
    ],
  },
  {
    id: "fruit-pizza-sugar-cookie",
    title: "Fruit Pizza on a Sugar Cookie",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "A giant sugar-cookie pizza topped with frosting and fruit!",
    emoji: "🍕",
    color: "#F8BBD0",
    category: "dessert",
    ingredients: [
      ["cookie", "1 large sugar cookie"],
      ["frosting", "2 tbsp frosting"],
      ["fruit", "sliced fruit"],
    ],
    steps: [
      ["Spread frosting on the cookie and arrange fruit on top.", ["cookie","frosting","fruit"]],
      ["Slice it like a pizza.", []],
    ],
  },
  {
    id: "apricot-coconut-energy-bites",
    title: "Apricot & Coconut Energy Bites",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Chewy apricot-coconut bites that fuel snack-time adventures!",
    emoji: "🥥",
    color: "#FFE0B2",
    category: "dessert",
    ingredients: [
      ["apricots", "1/2 cup dried apricots"],
      ["coconut", "1/4 cup shredded coconut"],
      ["honey", "1 tbsp honey"],
    ],
    steps: [
      ["Ask an adult to blend apricots until sticky.", ["apricots"], {"needsAdult":true,"adultReason":"Blenders need adult hands!","timerSeconds":30,"timerLabel":"Blend"}],
      ["Mix with coconut and honey, then roll into balls.", ["coconut","honey"]],
    ],
  },
  {
    id: "banana-nice-cream-one-ingredient",
    title: "Banana \"Nice Cream\" with One Ingredient",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Frozen bananas blended into creamy one-ingredient nice cream!",
    emoji: "🍦",
    color: "#FFF59D",
    category: "dessert",
    ingredients: [
      ["bananas", "2 frozen bananas"],
    ],
    steps: [
      ["Ask an adult to blend frozen bananas until they look like ice cream.", ["bananas"], {"needsAdult":true,"adultReason":"Blenders need adult hands!","timerSeconds":30,"timerLabel":"Blend"}],
      ["Eat it right away.", []],
    ],
  },
  {
    id: "strawberry-santas-whipped-cream",
    title: "Strawberry Santas with Whipped Cream",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Strawberries dressed up as tiny Santas with whipped cream!",
    emoji: "🎅",
    color: "#EF9A9A",
    category: "dessert",
    ingredients: [
      ["strawberries", "5 strawberries"],
      ["cream", "1/4 cup whipped cream"],
    ],
    steps: [
      ["Ask an adult to cut the tip off each strawberry.", [], {"needsAdult":true,"adultReason":"Cutting needs adult help!"}],
      ["Put whipped cream on the base and put the tip back on like a hat.", ["cream"]],
    ],
  },
  {
    id: "chocolate-dipped-strawberries-sprinkles",
    title: "Chocolate Dipped Strawberries with Sprinkles",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Strawberries dipped in chocolate and covered in sprinkles!",
    emoji: "🍓",
    color: "#F48FB1",
    category: "dessert",
    ingredients: [
      ["strawberries", "5 strawberries"],
      ["chips", "1/4 cup chocolate chips"],
      ["sprinkles", "sprinkles"],
    ],
    steps: [
      ["Ask an adult to melt the chocolate.", [], {"needsAdult":true,"adultReason":"Hot cooking needs adult help!"}],
      ["Dip strawberries in chocolate and then in sprinkles.", ["strawberries","sprinkles"]],
    ],
  },
  {
    id: "graham-cracker-houses-frosting",
    title: "Graham Cracker Houses with Frosting",
    cookTimeMins: 15,
    safety: "kid-solo",
    description: "Mini graham-cracker houses glued with frosting!",
    emoji: "🏠",
    color: "#D7CCC8",
    category: "dessert",
    ingredients: [
      ["graham", "4 graham crackers"],
      ["frosting", "2 tbsp frosting"],
      ["candies", "small candies"],
    ],
    steps: [
      ["Use frosting to stick crackers into a house shape.", ["frosting"]],
      ["Decorate with candies!", ["candies"]],
    ],
  },
  {
    id: "no-bake-lemon-bars-graham-crust",
    title: "No-Bake Lemon Bars with Graham Crust",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Zingy no-bake lemon bars on a graham cracker crust!",
    emoji: "🍋",
    color: "#FFF59D",
    category: "dessert",
    ingredients: [
      ["graham", "1 cup graham crumbs"],
      ["condensed", "1/2 cup condensed milk"],
      ["lemon-juice", "1 tbsp lemon juice"],
    ],
    steps: [
      ["Mix everything and press into a pan.", []],
      ["Chill and cut into squares.", [], {"timerSeconds":3600,"timerLabel":"Chill"}],
    ],
  },
  {
    id: "apple-nachos-caramel-drizzle",
    title: "Apple Nachos with Caramel Drizzle",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Apple nachos with caramel drizzle and chocolate chips!",
    emoji: "🍎",
    color: "#FFCC80",
    category: "dessert",
    ingredients: [
      ["apple", "1 apple (sliced)"],
      ["caramel", "1 tbsp caramel sauce"],
      ["chips", "1 tsp mini chocolate chips"],
    ],
    steps: [
      ["Lay apple slices on a plate.", ["apple"]],
      ["Drizzle with caramel and sprinkle with chips.", ["caramel","chips"]],
    ],
  },
  {
    id: "pb-celery-butterflies-pretzels",
    title: "Peanut Butter Celery Butterflies with Pretzels",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Celery butterflies with peanut butter bodies and pretzel wings!",
    emoji: "🦋",
    color: "#C5E1A5",
    category: "dessert",
    ingredients: [
      ["celery", "1 celery stick"],
      ["pb", "1 tbsp peanut butter"],
      ["pretzels", "2 pretzels"],
      ["raisins", "2 raisins"],
    ],
    steps: [
      ["Fill celery with peanut butter.", ["celery"]],
      ["Use pretzels as wings and raisins as eyes.", ["pretzels","raisins"]],
    ],
  },
  {
    id: "watermelon-pizza-coconut-flakes",
    title: "Watermelon Pizza with Coconut Flakes",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "A watermelon pizza slice topped with yogurt and coconut snow!",
    emoji: "🍉",
    color: "#F48FB1",
    category: "dessert",
    ingredients: [
      ["watermelon", "1 slice watermelon"],
      ["blueberries", "1/4 cup blueberries"],
      ["coconut-flakes", "1/4 cup coconut flakes"],
    ],
    steps: [
      ["Cut the watermelon into triangles.", ["watermelon"]],
      ["Sprinkle with berries and coconut flakes.", ["coconut-flakes"]],
    ],
  },
  {
    id: "chocolate-bark-mixed-nuts",
    title: "Chocolate Bark with Mixed Nuts",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Chocolate bark studded with mixed nuts — snap and share!",
    emoji: "🍫",
    color: "#4E342E",
    category: "dessert",
    ingredients: [
      ["chocolate", "1/2 cup melted chocolate"],
      ["nuts", "2 tbsp chopped nuts"],
    ],
    steps: [
      ["Spread chocolate on wax paper and sprinkle with nuts.", ["chocolate","nuts"]],
      ["Freeze until hard, then break into pieces.", [], {"timerSeconds":3600,"timerLabel":"Freeze"}],
    ],
  },
  {
    id: "no-bake-brownie-bites-dates-walnuts",
    title: "No-Bake Brownie Bites with Dates & Walnuts",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Date-and-walnut brownie bites that taste like fudge!",
    emoji: "🟤",
    color: "#5D4037",
    category: "dessert",
    ingredients: [
      ["walnuts", "1/2 cup walnuts"],
      ["dates", "1/2 cup dates"],
      ["cocoa", "1 tbsp cocoa powder"],
    ],
    steps: [
      ["Ask an adult to blend everything until sticky.", [], {"needsAdult":true,"adultReason":"Blenders need adult hands!","timerSeconds":30,"timerLabel":"Blend"}],
      ["Roll into small balls.", []],
    ],
  },
  {
    id: "fruit-rice-paper-rolls-mango",
    title: "Fruit Rice Paper Rolls with Mango",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Fresh mango rice-paper rolls — sweet summer wraps!",
    emoji: "🥭",
    color: "#FFCCBC",
    category: "dessert",
    ingredients: [
      ["rice-paper", "2 rice paper sheets"],
      ["mango-strawberries", "sliced mango and strawberries"],
    ],
    steps: [
      ["Dip rice paper in water and lay fruit in the middle.", ["rice-paper"]],
      ["Roll it up tight.", []],
    ],
  },
  {
    id: "yogurt-melts-small-dots",
    title: "Yogurt Melts in Small Dots",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Tiny frozen yogurt dots that melt on your tongue!",
    emoji: "💜",
    color: "#F8BBD0",
    category: "dessert",
    ingredients: [
      ["yogurt", "1/2 cup yogurt"],
    ],
    steps: [
      ["Squeeze small dots of yogurt onto a tray.", ["yogurt"]],
      ["Freeze until they are hard little drops.", [], {"timerSeconds":7200,"timerLabel":"Freeze"}],
    ],
  },
  {
    id: "trail-mix-popcorn-mms",
    title: "Trail Mix Popcorn with M&Ms",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Popcorn trail mix tossed with M&Ms for a movie-night crunch!",
    emoji: "🍿",
    color: "#FFE082",
    category: "dessert",
    ingredients: [
      ["popcorn", "2 cups popcorn"],
      ["m-ms", "1/4 cup M&Ms"],
      ["pretzels", "1/4 cup pretzels"],
    ],
    steps: [
      ["Toss everything together in a bowl for a sweet and salty snack.", []],
    ],
  },
  {
    id: "mini-fruit-tarts-vanilla-pudding",
    title: "Mini Fruit Tarts with Vanilla Pudding",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Mini tart shells filled with vanilla pudding and fruit jewels!",
    emoji: "🧁",
    color: "#F8BBD0",
    category: "dessert",
    ingredients: [
      ["tart", "4 mini tart shells"],
      ["pudding", "1/2 cup pudding"],
      ["fruit", "fruit slices"],
    ],
    steps: [
      ["Fill shells with pudding and top with fruit.", ["pudding","fruit"]],
    ],
  },
  {
    id: "chocolate-covered-bananas-stick",
    title: "Chocolate Covered Bananas on a Stick",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Banana halves on sticks dipped in chocolate and frozen!",
    emoji: "🍌",
    color: "#FFF59D",
    category: "dessert",
    ingredients: [
      ["banana", "1 banana"],
      ["chocolate", "1/4 cup melted chocolate"],
      ["popsicle", "popsicle sticks"],
    ],
    steps: [
      ["Put banana halves on sticks and dip in chocolate.", ["banana","chocolate"]],
      ["Freeze for a cool treat.", [], {"timerSeconds":3600,"timerLabel":"Freeze"}],
    ],
  },
  {
    id: "no-bake-granola-bars-honey",
    title: "No-Bake Granola Bars with Honey",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Chewy no-bake granola bars held together with honey!",
    emoji: "🍫",
    color: "#D7CCC8",
    category: "dessert",
    ingredients: [
      ["oats", "1 cup oats"],
      ["honey", "1/4 cup honey"],
      ["pb", "1/4 cup peanut butter"],
    ],
    steps: [
      ["Mix everything and press into a pan.", []],
      ["Chill and cut into bars.", [], {"timerSeconds":3600,"timerLabel":"Chill"}],
    ],
  },
  {
    id: "pbj-cracker-bites",
    title: "PB&J Cracker Bites",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Mini peanut-butter-and-jelly sandwiches on crackers!",
    emoji: "🍪",
    color: "#FFE0B2",
    category: "dessert",
    ingredients: [
      ["crackers", "4 crackers"],
      ["pb", "1 tsp peanut butter"],
      ["jelly", "1 tsp jelly"],
    ],
    steps: [
      ["Make tiny cracker sandwiches with peanut butter and jelly.", ["jelly"]],
    ],
  },
  {
    id: "fruit-cheese-skewers-grapes",
    title: "Fruit & Cheese Skewers with Grapes",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Grape and cheese skewers — snack kabobs for parties!",
    emoji: "🍇",
    color: "#CE93D8",
    category: "dessert",
    ingredients: [
      ["grapes", "Grapes"],
      ["cheese", "cheese cubes"],
    ],
    steps: [
      ["Thread grapes and cheese onto a stick for a quick snack.", ["grapes","cheese"]],
    ],
  },
  {
    id: "caramel-popcorn-sticky-fingers",
    title: "Caramel Popcorn with Sticky Fingers",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Sticky caramel popcorn that sticks to your fingers (in a good way)!",
    emoji: "🍿",
    color: "#FFCC80",
    category: "dessert",
    ingredients: [
      ["popcorn", "2 cups popcorn"],
      ["caramel", "2 tbsp caramel sauce"],
    ],
    steps: [
      ["Drizzle warm caramel over popcorn and toss to coat.", ["popcorn","caramel"]],
    ],
  },
  {
    id: "no-bake-coconut-macaroons-condensed-milk",
    title: "No-Bake Coconut Macaroons with Condensed Milk",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Coconut macaroons mixed with sweet condensed milk — no oven needed!",
    emoji: "🥥",
    color: "#FFF8E1",
    category: "dessert",
    ingredients: [
      ["coconut", "1 cup coconut"],
      ["condensed", "1/4 cup condensed milk"],
    ],
    steps: [
      ["Mix and form into small mounds. They are so sweet.", []],
    ],
  },
  {
    id: "pudding-dirt-cups-gummy-bears",
    title: "Pudding Dirt Cups with Gummy Bears",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Chocolate pudding dirt cups with crushed cookies and gummy bears!",
    emoji: "🐻",
    color: "#5D4037",
    category: "dessert",
    ingredients: [
      ["pudding", "1 cup pudding"],
      ["cookies", "2 crushed cookies"],
      ["gummy-bears", "gummy bears"],
    ],
    steps: [
      ["Put pudding in a cup, top with \"dirt\" cookies, and add gummy bears. Drinks.", ["pudding","cookies","gummy-bears"]],
    ],
  },
  {
    id: "virgin-mojito-mint-lime",
    title: "Virgin Mojito with Mint & Lime",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "A kid-friendly mojito with mint, lime, and bubbly soda!",
    emoji: "🍹",
    color: "#A5D6A7",
    category: "drinks",
    ingredients: [
      ["sparkling", "1 cup sparkling water"],
      ["lime", "1 tbsp lime juice"],
      ["mint", "mint leaves"],
    ],
    steps: [
      ["Mash mint in a glass, add lime juice and sparkling water.", ["sparkling","lime","mint"]],
    ],
  },
  {
    id: "simple-mango-lassi-yogurt",
    title: "Simple Mango Lassi with Yogurt",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Creamy mango lassi blended with yogurt — tropical and cool!",
    emoji: "🥭",
    color: "#FFE082",
    category: "drinks",
    ingredients: [
      ["mango-pulp", "1/2 cup mango pulp"],
      ["yogurt", "1/2 cup yogurt"],
    ],
    steps: [
      ["Ask an adult to blend until smooth and creamy.", [], {"needsAdult":true,"adultReason":"Blenders need adult hands!","timerSeconds":30,"timerLabel":"Blend"}],
    ],
  },
  {
    id: "shirley-temple-cherry-top",
    title: "Shirley Temple with a Cherry on Top",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Sparkling Shirley Temple with a bright cherry on top!",
    emoji: "🍒",
    color: "#EF9A9A",
    category: "drinks",
    ingredients: [
      ["soda", "1 cup lemon-lime soda"],
      ["syrup", "1 tbsp cherry syrup"],
      ["cherry", "1 cherry"],
    ],
    steps: [
      ["Mix soda and syrup, then add the cherry.", ["soda","syrup","cherry"]],
    ],
  },
  {
    id: "arnold-palmer-tea-lemonade",
    title: "Arnold Palmer with Tea & Lemonade",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Half iced tea, half lemonade — the classic Arnold Palmer!",
    emoji: "🍋",
    color: "#FFF59D",
    category: "drinks",
    ingredients: [
      ["tea", "1/2 cup iced tea"],
      ["lemonade", "1/2 cup lemonade"],
    ],
    steps: [
      ["Mix tea and lemonade for a classic summer drink.", ["tea","lemonade"]],
    ],
  },
  {
    id: "fruit-infused-ice-cubes-water",
    title: "Fruit Infused Ice Cubes for Water",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Fancy water with fruit ice cubes that slowly flavor every sip!",
    emoji: "🧊",
    color: "#B3E5FC",
    category: "drinks",
    ingredients: [
      ["water", "Water"],
      ["fruit", "small fruit pieces"],
    ],
    steps: [
      ["Put fruit in an ice tray, fill with water, and freeze.", ["water","fruit"], {"timerSeconds":10800,"timerLabel":"Freeze"}],
    ],
  },
  {
    id: "warm-spiced-apple-juice-nutmeg",
    title: "Warm Spiced Apple Juice with Nutmeg",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Warm apple juice with a pinch of nutmeg — cozy cup magic!",
    emoji: "🍎",
    color: "#FFCC80",
    category: "drinks",
    ingredients: [
      ["apple", "1 cup apple juice"],
      ["nutmeg", "a pinch of nutmeg"],
    ],
    steps: [
      ["Ask an adult to warm the juice and stir in the nutmeg.", ["nutmeg"], {"needsAdult":true,"adultReason":"Hot cooking needs adult help!","timerSeconds":60,"timerLabel":"Warm"}],
    ],
  },
  {
    id: "blueberry-yogurt-drink-jar",
    title: "Blueberry Yogurt Drink in a Jar",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "A shakeable blueberry yogurt drink in a jar!",
    emoji: "🫐",
    color: "#CE93D8",
    category: "drinks",
    ingredients: [
      ["milk", "1/2 cup milk"],
      ["yogurt", "1/4 cup blueberry yogurt"],
    ],
    steps: [
      ["Shake everything in a jar until mixed.", []],
    ],
  },
  {
    id: "peppermint-hot-chocolate-candy-canes",
    title: "Peppermint Hot Chocolate with Candy Canes",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Peppermint hot chocolate stirred with a candy cane!",
    emoji: "☕",
    color: "#D7CCC8",
    category: "drinks",
    ingredients: [
      ["chocolate", "1 cup hot chocolate"],
      ["candy-cane", "1 candy cane"],
    ],
    steps: [
      ["Use the candy cane to stir your hot chocolate!", ["chocolate","candy-cane"]],
    ],
  },
  {
    id: "peach-ginger-fizz-soda",
    title: "Peach & Ginger Fizz with Soda",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Peachy ginger ale fizz that sparkles in the glass!",
    emoji: "🍑",
    color: "#FFCCBC",
    category: "drinks",
    ingredients: [
      ["peach", "1/2 cup peach juice"],
      ["ginger-ale", "1/2 cup ginger ale"],
    ],
    steps: [
      ["Mix juice and ginger ale for a fizzy treat.", ["ginger-ale"]],
    ],
  },
  {
    id: "cherry-limeade-sour-lime",
    title: "Cherry Limeade with Sour Lime",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Tangy cherry limeade with a sour lime kick!",
    emoji: "🍒",
    color: "#F48FB1",
    category: "drinks",
    ingredients: [
      ["water", "1 cup water"],
      ["lime", "1 tbsp lime juice"],
      ["syrup", "1 tbsp cherry syrup"],
    ],
    steps: [
      ["Mix everything for a bright red drink.", []],
    ],
  },
  {
    id: "banana-date-smoothie-caramel-taste",
    title: "Banana & Date Smoothie with Caramel Taste",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Banana and date smoothie that tastes like caramel!",
    emoji: "🍌",
    color: "#FFE082",
    category: "drinks",
    ingredients: [
      ["banana", "1 banana"],
      ["dates", "2 dates"],
      ["milk", "1/2 cup milk"],
    ],
    steps: [
      ["Ask an adult to blend until smooth.", [], {"needsAdult":true,"adultReason":"Blenders need adult hands!","timerSeconds":30,"timerLabel":"Blend"}],
    ],
  },
  {
    id: "cucumber-mint-refresher-water",
    title: "Cucumber & Mint Refresher Water",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Cool cucumber-mint water that tastes like a spa day!",
    emoji: "🥒",
    color: "#C5E1A5",
    category: "drinks",
    ingredients: [
      ["water", "1 cup water"],
      ["cucumber", "cucumber slices"],
      ["mint", "mint leaf"],
    ],
    steps: [
      ["Let the veggies sit in the water for a fresh taste.", ["water"], {"timerSeconds":300,"timerLabel":"Steep"}],
    ],
  },
  {
    id: "frozen-hot-chocolate-slushie",
    title: "Frozen Hot Chocolate Slushie",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Hot chocolate turned into an icy frozen slushie!",
    emoji: "🍫",
    color: "#4E342E",
    category: "drinks",
    ingredients: [
      ["milk", "1/2 cup milk"],
      ["cocoa", "1 tbsp cocoa mix"],
      ["ice", "1 cup ice"],
    ],
    steps: [
      ["Ask an adult to blend until snowy and thick.", [], {"needsAdult":true,"adultReason":"Blenders need adult hands!","timerSeconds":30,"timerLabel":"Blend"}],
    ],
  },
  {
    id: "tropical-fruit-punch-pineapple",
    title: "Tropical Fruit Punch with Pineapple",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Tropical pineapple punch for beach vibes at home!",
    emoji: "🍍",
    color: "#FFCC80",
    category: "drinks",
    ingredients: [
      ["pineapple", "1/4 cup pineapple juice"],
      ["orange", "1/4 cup orange juice"],
    ],
    steps: [
      ["Mix the juices for a tropical punch.", []],
    ],
  },
  {
    id: "iced-vanilla-milk-jar",
    title: "Iced Vanilla Milk with a Jar",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Cold vanilla milk shaken in a jar until frothy!",
    emoji: "🥛",
    color: "#FFF8E1",
    category: "drinks",
    ingredients: [
      ["milk", "1 cup milk"],
      ["vanilla", "1/4 tsp vanilla"],
      ["sugar", "1 tsp sugar"],
    ],
    steps: [
      ["Shake everything in a jar with ice.", []],
    ],
  },
  {
    id: "strawberry-mint-water-kids",
    title: "Strawberry Mint Water for Kids",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Pretty strawberry-mint water for sipping in the sun!",
    emoji: "🍓",
    color: "#F8BBD0",
    category: "drinks",
    ingredients: [
      ["water", "1 cup water"],
      ["strawberry", "1 strawberry"],
      ["mint", "1 mint leaf"],
    ],
    steps: [
      ["Add fruit and mint to your water for a pretty drink.", ["water","mint"]],
    ],
  },
  {
    id: "pineapple-ginger-ale-bubbles",
    title: "Pineapple Ginger Ale Bubbles",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Pineapple juice plus ginger ale bubbles — sweet and zippy!",
    emoji: "🍍",
    color: "#FFF59D",
    category: "drinks",
    ingredients: [
      ["pineapple", "1/2 cup pineapple juice"],
      ["ginger-ale", "1/2 cup ginger ale"],
    ],
    steps: [
      ["Mix and enjoy the bubbles!", []],
    ],
  },
  {
    id: "green-apple-slushie-ice",
    title: "Green Apple Slushie with Ice",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "A green apple slushie blended with ice until frosty!",
    emoji: "🍏",
    color: "#C5E1A5",
    category: "drinks",
    ingredients: [
      ["apple", "1/2 cup apple juice"],
      ["ice", "1 cup ice"],
    ],
    steps: [
      ["Ask an adult to blend until snowy and green.", [], {"needsAdult":true,"adultReason":"Blenders need adult hands!","timerSeconds":30,"timerLabel":"Blend"}],
    ],
  },
  {
    id: "blackberry-fizz-sparkling-water",
    title: "Blackberry Fizz with Sparkling Water",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Blackberry juice topped with sparkling water fizz!",
    emoji: "🫐",
    color: "#CE93D8",
    category: "drinks",
    ingredients: [
      ["blackberry", "1/2 cup blackberry juice"],
      ["sparkling", "1/2 cup sparkling water"],
    ],
    steps: [
      ["Mix for a deep purple drink.", []],
    ],
  },
  {
    id: "coconut-water-punch-beach",
    title: "Coconut Water Punch for the Beach",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Coconut water punch that tastes like a beach vacation!",
    emoji: "🥥",
    color: "#B2EBF2",
    category: "drinks",
    ingredients: [
      ["coconut", "1/2 cup coconut water"],
      ["pineapple", "1/2 cup pineapple juice"],
    ],
    steps: [
      ["Mix and imagine you are on vacation.", []],
    ],
  },
  {
    id: "spiced-pear-juice-cinnamon",
    title: "Spiced Pear Juice with Cinnamon",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Pear juice stirred with cinnamon for a spiced sip!",
    emoji: "🍐",
    color: "#FFCC80",
    category: "drinks",
    ingredients: [
      ["pear", "1 cup pear juice"],
      ["cinnamon", "a pinch of cinnamon"],
    ],
    steps: [
      ["Stir cinnamon into the pear juice.", ["pear","cinnamon"]],
    ],
  },
  {
    id: "melon-mint-smoothie-yogurt",
    title: "Melon & Mint Smoothie with Yogurt",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Honeydew, mint, and yogurt blended into a cool green smoothie!",
    emoji: "🍈",
    color: "#C5E1A5",
    category: "drinks",
    ingredients: [
      ["melon", "1 cup melon"],
      ["mint", "1 mint leaf"],
      ["yogurt", "1/4 cup yogurt"],
    ],
    steps: [
      ["Ask an adult to blend until smooth and light green.", [], {"needsAdult":true,"adultReason":"Blenders need adult hands!","timerSeconds":30,"timerLabel":"Blend"}],
    ],
  },
  {
    id: "vanilla-steamer-foamy-milk",
    title: "Vanilla Steamer with Foamy Milk",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Warm foamy vanilla milk — a cafe steamer at home!",
    emoji: "☕",
    color: "#FFF8E1",
    category: "drinks",
    ingredients: [
      ["milk", "1 cup milk"],
      ["sugar", "1 tsp sugar"],
      ["vanilla", "1/4 tsp vanilla"],
    ],
    steps: [
      ["Ask an adult to warm the milk and stir until foamy.", ["milk"], {"needsAdult":true,"adultReason":"Hot cooking needs adult help!","timerSeconds":60,"timerLabel":"Warm"}],
    ],
  },
  {
    id: "berry-sparkler-dancing-bubbles",
    title: "Berry Sparkler with Dancing Bubbles",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Berry juice with dancing sparkling-water bubbles!",
    emoji: "✨",
    color: "#F48FB1",
    category: "drinks",
    ingredients: [
      ["berry", "1/2 cup berry juice"],
      ["sparkling", "1/2 cup sparkling water"],
    ],
    steps: [
      ["Mix and watch the bubbles dance.", []],
    ],
  },
  {
    id: "rainbow-layered-juice-sunset",
    title: "Rainbow Layered Juice Sunset",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Grenadine, orange, and blue layers stacked into a sunset rainbow!",
    emoji: "🌈",
    color: "#90CAF9",
    category: "drinks",
    ingredients: [
      ["grenadine", "1/4 cup grenadine"],
      ["orange", "1/4 cup orange juice"],
      ["blue-sports", "1/4 cup blue sports drink"],
    ],
    steps: [
      ["Ask an adult to pour layers slowly over a spoon to keep them separate. It looks like a sunset.", [], {"needsAdult":true,"adultReason":"Ask an adult for help with this step!"}],
    ],
  },
];

function escape(s) {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function stepToTs(step, idx) {
  const [instruction, ingredientIds = [], extra = {}] = step;
  const lines = [
    `      {`,
    `        id: "s${idx + 1}",`,
    `        instruction: "${escape(instruction)}",`,
  ];
  if (extra.timerSeconds) {
    lines.push(`        timerSeconds: ${extra.timerSeconds},`);
    if (extra.timerLabel) lines.push(`        timerLabel: "${escape(extra.timerLabel)}",`);
  }
  lines.push(
    `        ingredientIds: [${ingredientIds.map((id) => `"${id}"`).join(", ")}],`,
  );
  if (extra.needsAdult) {
    lines.push(`        needsAdult: true,`);
    if (extra.adultReason) lines.push(`        adultReason: "${escape(extra.adultReason)}",`);
  }
  lines.push(`      },`);
  return lines.join("\n");
}

function recipeToTs(r) {
  const pattern =
    "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)";
  return `  {
    id: "${r.id}",
    title: "${escape(r.title)}",
    cookTimeMins: ${r.cookTimeMins},
    safety: "${r.safety}",
    description: "${escape(r.description)}",
    emoji: "${r.emoji}",
    placeholderColor: "${r.color}",
    pattern: "${pattern}",
    suggestedCookbook: "${r.category}",
    baseServings: 1,
    imageSrc: "/recipes/${r.id}.svg",
    ingredients: [
${r.ingredients.map(([id, name]) => `      { id: "${id}", name: "${escape(name)}" },`).join("\n")}
    ],
    steps: [
${r.steps.map((s, i) => stepToTs(s, i)).join("\n")}
    ],
  },`;
}

const outTs = `import type { Recipe } from "./types";

/** Extra mini-chef recipes (batch 4) */
export const MORE_RECIPES_BATCH4: Recipe[] = [
${recipes.map(recipeToTs).join("\n")}
];
`;

fs.writeFileSync(path.join("lib", "more-recipes-batch4.ts"), outTs);

const dir = path.join("public", "recipes");
fs.mkdirSync(dir, { recursive: true });

for (const r of recipes) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 520 520">
  <rect width="520" height="520" fill="${r.color}"/>
  <circle cx="260" cy="250" r="120" fill="rgba(255,255,255,0.35)"/>
  <text x="260" y="280" text-anchor="middle" font-size="120">${r.emoji}</text>
</svg>
`;
  fs.writeFileSync(path.join(dir, `${r.id}.svg`), svg);
}

console.log(`Wrote ${recipes.length} recipes + SVGs`);
