/**
 * Generates lib/more-recipes-batch3.ts and SVG placeholders for batch 3 (100 recipes, IDs 76-175).
 * Run: node scripts/generate-batch3.js
 */
const fs = require("fs");
const path = require("path");

/** @typedef {{ id: string, name: string }} Ing */
/** @typedef {{ instruction: string, ingredientIds?: string[], needsAdult?: boolean, adultReason?: string, timerSeconds?: number, timerLabel?: string }} StepIn */

const recipes = [
  // Breakfast 76-100
  {
    id: "avocado-toast-sun-egg",
    title: 'Avocado Toast with "Sun" Egg',
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Creamy avocado toast topped with a sunny egg — breakfast that looks like morning!",
    emoji: "🥑",
    color: "#A5D6A7",
    category: "breakfast",
    ingredients: [
      ["toast", "1 slice of toast"],
      ["avocado", "1/2 ripe avocado"],
      ["egg", "1 egg"],
      ["salt", "A pinch of salt"],
    ],
    steps: [
      ["Mash the avocado on the toast and sprinkle with salt.", ["toast", "avocado", "salt"]],
      ["Ask an adult to fry an egg sunny-side up.", ["egg"], { needsAdult: true, adultReason: "Hot stove and eggs need adult help!" }],
      ["Slide the egg onto the avocado toast like a little sun.", []],
      ["Eat your sunny breakfast!", []],
    ],
  },
  {
    id: "oatmeal-raisin-breakfast-cookies",
    title: "Oatmeal Raisin Breakfast Cookies",
    cookTimeMins: 15,
    safety: "adult-helper",
    description: "Soft banana-oat cookies studded with raisins — cookies you can eat for breakfast!",
    emoji: "🍪",
    color: "#D7CCC8",
    category: "breakfast",
    ingredients: [
      ["banana", "1 ripe banana"],
      ["oats", "1 cup oats"],
      ["raisins", "1/4 cup raisins"],
    ],
    steps: [
      ["Mash the banana in a bowl.", ["banana"]],
      ["Stir in the oats and raisins until sticky.", ["oats", "raisins"]],
      ["Scoop spoonfuls onto a baking sheet and flatten slightly.", []],
      ["Ask an adult to bake at 350°F for 10–12 minutes.", [], { needsAdult: true, adultReason: "Hot oven!", timerSeconds: 660, timerLabel: "Bake cookies" }],
      ["Cool a bit, then nibble your breakfast cookies!", []],
    ],
  },
  {
    id: "super-berry-smoothie-bowl",
    title: "Super Berry Smoothie Bowl",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "A thick purple berry bowl topped with crunchy granola and seeds — spoonable sunshine!",
    emoji: "🫐",
    color: "#CE93D8",
    category: "breakfast",
    ingredients: [
      ["berries", "1 cup frozen berries"],
      ["yogurt", "1/2 cup yogurt"],
      ["granola", "2 tbsp granola"],
      ["seeds", "1 tsp pumpkin seeds"],
    ],
    steps: [
      ["Put the frozen berries and yogurt in the blender.", ["berries", "yogurt"]],
      ["Ask an adult to blend until thick and smooth.", [], { needsAdult: true, adultReason: "Blenders need adult hands!", timerSeconds: 30, timerLabel: "Blend bowl" }],
      ["Pour into a bowl and top with granola and pumpkin seeds.", ["granola", "seeds"]],
      ["Dig in with a spoon!", []],
    ],
  },
  {
    id: "pancake-muffins",
    title: "Pancake Muffins",
    cookTimeMins: 20,
    safety: "adult-helper",
    description: "Pancake batter baked in muffin cups with blueberries or chips — grab-and-go flapjacks!",
    emoji: "🧁",
    color: "#FFE0B2",
    category: "breakfast",
    ingredients: [
      ["mix", "1 cup pancake mix (prepared per package)"],
      ["mixins", "1/2 cup blueberries or chocolate chips"],
    ],
    steps: [
      ["Stir the pancake mix until smooth.", ["mix"]],
      ["Fold in blueberries or chocolate chips.", ["mixins"]],
      ["Spoon the batter into muffin cups.", []],
      ["Ask an adult to bake at 350°F for 12–15 minutes.", [], { needsAdult: true, adultReason: "Hot oven!", timerSeconds: 780, timerLabel: "Bake muffins" }],
      ["Cool slightly and pop out your pancake muffins!", []],
    ],
  },
  {
    id: "yogurt-fruit-breakfast-pops",
    title: "Yogurt & Fruit Breakfast Pops",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Creamy yogurt and fruit frozen on sticks — breakfast popsicles!",
    emoji: "🍭",
    color: "#F8BBD0",
    category: "breakfast",
    ingredients: [
      ["yogurt", "1 cup yogurt"],
      ["fruit", "1/2 cup chopped fruit"],
      ["sticks", "Popsicle sticks"],
    ],
    steps: [
      ["Stir yogurt and fruit together.", ["yogurt", "fruit"]],
      ["Spoon into popsicle molds or small cups.", []],
      ["Add sticks and freeze until solid.", ["sticks"], { timerSeconds: 10800, timerLabel: "Freeze pops" }],
      ["Pop them out and enjoy a chilly breakfast!", []],
    ],
  },
  {
    id: "egg-in-a-hole",
    title: "Egg in a Hole",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Toast with a window in the middle and an egg cooked right inside — classic kid magic!",
    emoji: "🍳",
    color: "#FFF59D",
    category: "breakfast",
    ingredients: [
      ["bread", "1 slice of bread"],
      ["butter", "1 tsp butter"],
      ["egg", "1 egg"],
    ],
    steps: [
      ["Ask an adult to cut a circle hole in the bread.", ["bread"], { needsAdult: true, adultReason: "Cutting needs a knife or cookie cutter help!" }],
      ["Ask an adult to melt butter in a pan, toast both sides of the bread, then crack the egg into the hole.", ["butter", "egg"], { needsAdult: true, adultReason: "Hot pan and eggs!" }],
      ["Cook until the egg white is set.", []],
      ["Slide onto a plate and dig in!", []],
    ],
  },
  {
    id: "mini-spinach-cheese-frittatas",
    title: "Mini Spinach & Cheese Frittatas",
    cookTimeMins: 20,
    safety: "adult-helper",
    description: "Tiny muffin-tin egg cups packed with spinach and cheese — protein power bites!",
    emoji: "🥬",
    color: "#C5E1A5",
    category: "breakfast",
    ingredients: [
      ["eggs", "4 eggs"],
      ["spinach", "1/2 cup chopped spinach"],
      ["cheese", "1/4 cup shredded cheese"],
    ],
    steps: [
      ["Whisk the eggs in a bowl.", ["eggs"]],
      ["Stir in spinach and cheese.", ["spinach", "cheese"]],
      ["Pour into greased muffin cups.", []],
      ["Ask an adult to bake at 350°F for 15 minutes.", [], { needsAdult: true, adultReason: "Hot oven!", timerSeconds: 900, timerLabel: "Bake frittatas" }],
      ["Cool a minute, then pop out and eat!", []],
    ],
  },
  {
    id: "baked-oatmeal-squares",
    title: "Baked Oatmeal Squares",
    cookTimeMins: 25,
    safety: "adult-helper",
    description: "Warm cinnamon oatmeal baked into cuttable squares — cozy breakfast cake!",
    emoji: "🟫",
    color: "#BCAAA4",
    category: "breakfast",
    ingredients: [
      ["oats", "2 cups oats"],
      ["milk", "1 1/2 cups milk"],
      ["egg", "1 egg"],
      ["honey", "2 tbsp honey"],
      ["cinnamon", "1 tsp cinnamon"],
    ],
    steps: [
      ["Mix oats, milk, egg, honey, and cinnamon in a bowl.", ["oats", "milk", "egg", "honey", "cinnamon"]],
      ["Pour into a greased baking dish.", []],
      ["Ask an adult to bake at 350°F for 20 minutes.", [], { needsAdult: true, adultReason: "Hot oven!", timerSeconds: 1200, timerLabel: "Bake oatmeal" }],
      ["Cool, cut into squares, and serve!", []],
    ],
  },
  {
    id: "pb-banana-power-wraps",
    title: "Peanut Butter Banana Power Wraps",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "A tortilla rolled with peanut butter, banana, and granola — fuel for big adventures!",
    emoji: "🌯",
    color: "#FFE082",
    category: "breakfast",
    ingredients: [
      ["tortilla", "1 flour tortilla"],
      ["pb", "2 tbsp peanut butter (or alternative)"],
      ["banana", "1 banana"],
      ["granola", "2 tbsp granola"],
    ],
    steps: [
      ["Spread peanut butter on the tortilla.", ["tortilla", "pb"]],
      ["Place the banana in the middle and sprinkle granola.", ["banana", "granola"]],
      ["Roll it up tightly.", []],
      ["Bite into your power wrap!", []],
    ],
  },
  {
    id: "berry-mug-cake",
    title: "Berry Mug Cake",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "A fluffy blueberry cake that cooks in a mug in one minute — dessert-for-breakfast vibes!",
    emoji: "🫐",
    color: "#E1BEE7",
    category: "breakfast",
    ingredients: [
      ["flour", "4 tbsp flour"],
      ["baking-powder", "1/4 tsp baking powder"],
      ["maple", "1 tbsp maple syrup"],
      ["milk", "3 tbsp milk"],
      ["blueberries", "2 tbsp blueberries"],
    ],
    steps: [
      ["Mix flour, baking powder, maple, and milk in a mug.", ["flour", "baking-powder", "maple", "milk"]],
      ["Drop in the blueberries and stir gently.", ["blueberries"]],
      ["Ask an adult to microwave for 1 minute.", [], { needsAdult: true, adultReason: "Hot mug and microwave!", timerSeconds: 60, timerLabel: "Microwave cake" }],
      ["Cool a bit, then spoon up your mug cake!", []],
    ],
  },
  {
    id: "cottage-cheese-pineapple-islands",
    title: "Cottage Cheese Pineapple Islands",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Pineapple rings as islands with cottage cheese seas and a cherry treasure!",
    emoji: "🏝️",
    color: "#FFECB3",
    category: "breakfast",
    ingredients: [
      ["cottage", "1/2 cup cottage cheese"],
      ["pineapple", "2 pineapple rings"],
      ["cherry", "2 cherries"],
    ],
    steps: [
      ["Place pineapple rings on a plate.", ["pineapple"]],
      ["Spoon cottage cheese into the centers like little islands.", ["cottage"]],
      ["Top each with a cherry treasure.", ["cherry"]],
      ["Sail into breakfast!", []],
    ],
  },
  {
    id: "cereal-yogurt-parfait",
    title: "Cereal & Yogurt Parfait",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Layers of yogurt, crunchy cereal, and strawberries — a parfait you build yourself!",
    emoji: "🍨",
    color: "#F48FB1",
    category: "breakfast",
    ingredients: [
      ["yogurt", "1 cup yogurt"],
      ["cereal", "1/2 cup cereal"],
      ["strawberries", "1/2 cup sliced strawberries"],
    ],
    steps: [
      ["Spoon yogurt into a glass or bowl.", ["yogurt"]],
      ["Add a layer of cereal, then strawberries.", ["cereal", "strawberries"]],
      ["Repeat the layers until everything is used.", []],
      ["Grab a spoon and crunch away!", []],
    ],
  },
  {
    id: "toasted-waffle-sandwich",
    title: "Toasted Waffle Sandwich",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Crispy waffles sandwiched with cream cheese and jam — sweet breakfast hug!",
    emoji: "🧇",
    color: "#FFCC80",
    category: "breakfast",
    ingredients: [
      ["waffles", "2 frozen waffles"],
      ["cream-cheese", "2 tbsp cream cheese"],
      ["jam", "1 tbsp jam"],
    ],
    steps: [
      ["Ask an adult to toast the waffles until golden.", ["waffles"], { needsAdult: true, adultReason: "Toaster gets hot!" }],
      ["Spread cream cheese on one waffle and jam on the other.", ["cream-cheese", "jam"]],
      ["Press them together into a sandwich.", []],
      ["Bite into your waffle sandwich!", []],
    ],
  },
  {
    id: "breakfast-apple-nachos",
    title: "Breakfast Apple Nachos",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Apple slices loaded with peanut butter drizzle, yogurt, and raisins — nacho style!",
    emoji: "🍎",
    color: "#EF9A9A",
    category: "breakfast",
    ingredients: [
      ["apple", "1 apple"],
      ["pb", "2 tbsp peanut butter (or alternative)"],
      ["yogurt", "2 tbsp yogurt"],
      ["raisins", "2 tbsp raisins"],
    ],
    steps: [
      ["Ask an adult to slice the apple into thin wedges.", ["apple"], { needsAdult: true, adultReason: "Apple slicing needs a knife!" }],
      ["Arrange the slices on a plate like nachos.", []],
      ["Drizzle peanut butter and yogurt over the top.", ["pb", "yogurt"]],
      ["Sprinkle raisins and dig in!", ["raisins"]],
    ],
  },
  {
    id: "mini-pancake-skewers",
    title: "Mini Pancake Skewers",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Mini pancakes stacked with strawberries and grapes on sticks — breakfast kebabs!",
    emoji: "🍡",
    color: "#FFAB91",
    category: "breakfast",
    ingredients: [
      ["pancakes", "6 mini pancakes (warmed)"],
      ["strawberries", "6 strawberry halves"],
      ["grapes", "6 grapes"],
    ],
    steps: [
      ["Ask an adult to warm the mini pancakes if needed.", ["pancakes"], { needsAdult: true, adultReason: "Heating needs adult help!" }],
      ["Thread pancakes, strawberries, and grapes onto skewers.", ["strawberries", "grapes"]],
      ["Arrange on a plate.", []],
      ["Pull off bites and enjoy!", []],
    ],
  },
  {
    id: "simple-cheese-scones",
    title: "Simple Cheese Scones",
    cookTimeMins: 20,
    safety: "adult-helper",
    description: "Cheesy, fluffy scones from self-rising flour — bakery breakfast at home!",
    emoji: "🧀",
    color: "#FFE082",
    category: "breakfast",
    ingredients: [
      ["flour", "2 cups self-rising flour"],
      ["cheese", "1 cup shredded cheese"],
      ["milk", "3/4 cup milk"],
    ],
    steps: [
      ["Mix flour and cheese in a bowl.", ["flour", "cheese"]],
      ["Stir in milk until a soft dough forms.", ["milk"]],
      ["Pat into a round and cut into wedges on a baking sheet.", []],
      ["Ask an adult to bake at 400°F for 12 minutes.", [], { needsAdult: true, adultReason: "Hot oven!", timerSeconds: 720, timerLabel: "Bake scones" }],
      ["Cool slightly and enjoy warm!", []],
    ],
  },
  {
    id: "breakfast-pancake-tacos",
    title: "Breakfast Pancake Tacos",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Soft pancakes folded like tacos and filled with yogurt and fruit — taco Tuesday for breakfast!",
    emoji: "🌮",
    color: "#FFCC80",
    category: "breakfast",
    ingredients: [
      ["pancakes", "2 soft pancakes"],
      ["yogurt", "1/4 cup yogurt"],
      ["fruit", "1/2 cup chopped fruit"],
    ],
    steps: [
      ["Lay pancakes flat like taco shells.", ["pancakes"]],
      ["Spoon yogurt down the middle.", ["yogurt"]],
      ["Pile on fruit and fold.", ["fruit"]],
      ["Eat taco-style!", []],
    ],
  },
  {
    id: "nutella-strawberry-toast",
    title: "Nutella & Strawberry Toast",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Toasty bread with chocolate-hazelnut spread and juicy strawberry slices — fancy and fast!",
    emoji: "🍓",
    color: "#F48FB1",
    category: "breakfast",
    ingredients: [
      ["bread", "1 slice of bread"],
      ["nutella", "1 tbsp Nutella"],
      ["strawberries", "3–4 sliced strawberries"],
    ],
    steps: [
      ["Ask an adult to toast the bread.", ["bread"], { needsAdult: true, adultReason: "Toaster gets hot!" }],
      ["Spread Nutella on the warm toast.", ["nutella"]],
      ["Arrange strawberry slices on top.", ["strawberries"]],
      ["Bite into chocolate-berry bliss!", []],
    ],
  },
  {
    id: "hard-boiled-egg-sailboats",
    title: "Hard Boiled Egg Sailboats",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Hard-boiled egg halves with cheese sail flags on toothpicks — ahoy, breakfast!",
    emoji: "⛵",
    color: "#FFF9C4",
    category: "breakfast",
    ingredients: [
      ["egg", "1 hard-boiled egg"],
      ["cheese", "1 slice of cheese"],
      ["toothpick", "1 toothpick"],
    ],
    steps: [
      ["Ask an adult to peel and halve the egg if needed.", ["egg"], { needsAdult: true, adultReason: "Peeling or cutting may need help!" }],
      ["Cut a cheese triangle for a sail.", ["cheese"]],
      ["Poke the toothpick through the cheese and into the egg half.", ["toothpick"]],
      ["Set sail and eat your boat!", []],
    ],
  },
  {
    id: "breakfast-quesadilla",
    title: "Breakfast Quesadilla",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "A tortilla stuffed with scrambled egg and melty cheese — breakfast folded in half!",
    emoji: "🧀",
    color: "#FFD54F",
    category: "breakfast",
    ingredients: [
      ["tortilla", "1 flour tortilla"],
      ["egg", "1 scrambled egg (cooked)"],
      ["cheese", "1/4 cup shredded cheese"],
    ],
    steps: [
      ["Scatter cheese and scrambled egg on half the tortilla.", ["tortilla", "egg", "cheese"]],
      ["Fold the tortilla over.", []],
      ["Ask an adult to warm it in a pan until the cheese melts.", [], { needsAdult: true, adultReason: "Hot pan!" }],
      ["Cut into wedges and dig in!", []],
    ],
  },
  {
    id: "granola-yogurt-bark",
    title: "Granola Yogurt Bark",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Greek yogurt frozen into snap-apart bark with granola and honey — icy breakfast candy!",
    emoji: "🧊",
    color: "#B39DDB",
    category: "breakfast",
    ingredients: [
      ["yogurt", "1 cup Greek yogurt"],
      ["granola", "1/3 cup granola"],
      ["honey", "1 tsp honey"],
    ],
    steps: [
      ["Line a tray with wax paper.", []],
      ["Spread yogurt in a thin layer.", ["yogurt"]],
      ["Sprinkle granola and drizzle honey.", ["granola", "honey"]],
      ["Freeze until hard.", [], { timerSeconds: 7200, timerLabel: "Freeze bark" }],
      ["Break into pieces and snack!", []],
    ],
  },
  {
    id: "pumpkin-spice-overnight-oats",
    title: "Pumpkin Spice Overnight Oats",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Oats mixed with pumpkin and cinnamon that get creamy overnight — fall in a jar!",
    emoji: "🎃",
    color: "#FFB74D",
    category: "breakfast",
    ingredients: [
      ["oats", "1/2 cup oats"],
      ["milk", "1/2 cup milk"],
      ["pumpkin", "2 tbsp pumpkin puree"],
      ["cinnamon", "1/2 tsp cinnamon"],
    ],
    steps: [
      ["Mix oats, milk, pumpkin, and cinnamon in a jar.", ["oats", "milk", "pumpkin", "cinnamon"]],
      ["Stir well so everything is combined.", []],
      ["Optional: chill a few minutes, or leave in the fridge overnight.", [], { timerSeconds: 300, timerLabel: "Optional chill — or skip & wait overnight" }],
      ["In the morning, stir and enjoy!", []],
    ],
  },
  {
    id: "breakfast-sliders",
    title: "Breakfast Sliders",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Mini rolls stuffed with scrambled egg and cheese — tiny breakfast burgers!",
    emoji: "🍔",
    color: "#FFCC80",
    category: "breakfast",
    ingredients: [
      ["rolls", "2 mini rolls"],
      ["egg", "1 scrambled egg (cooked)"],
      ["cheese", "2 slices of cheese"],
    ],
    steps: [
      ["Split the mini rolls open.", ["rolls"]],
      ["Add scrambled egg and cheese.", ["egg", "cheese"]],
      ["Close the sliders.", []],
      ["Munch your mini breakfast burgers!", []],
    ],
  },
  {
    id: "peach-almond-yogurt-bowl",
    title: "Peach & Almond Yogurt Bowl",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Creamy yogurt topped with juicy peach and crunchy almonds — simple and sunny!",
    emoji: "🍑",
    color: "#FFAB91",
    category: "breakfast",
    ingredients: [
      ["yogurt", "1 cup yogurt"],
      ["peach", "1 peach, sliced"],
      ["almonds", "2 tbsp sliced almonds"],
    ],
    steps: [
      ["Spoon yogurt into a bowl.", ["yogurt"]],
      ["Arrange peach slices on top.", ["peach"]],
      ["Sprinkle almonds over everything.", ["almonds"]],
      ["Scoop and savor!", []],
    ],
  },
  {
    id: "ricotta-honey-toast",
    title: "Ricotta & Honey Toast",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Toasty bread with fluffy ricotta and a golden honey drizzle — cafe-style breakfast!",
    emoji: "🍯",
    color: "#FFF8E1",
    category: "breakfast",
    ingredients: [
      ["bread", "1 slice of bread"],
      ["ricotta", "2 tbsp ricotta"],
      ["honey", "1 tsp honey"],
    ],
    steps: [
      ["Ask an adult to toast the bread.", ["bread"], { needsAdult: true, adultReason: "Toaster gets hot!" }],
      ["Spread ricotta on the warm toast.", ["ricotta"]],
      ["Drizzle honey over the top.", ["honey"]],
      ["Take a fancy bite!", []],
    ],
  },

  // Dinner 101-125
  {
    id: "mini-meatball-subs",
    title: "Mini Meatball Subs",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Warm rolls stuffed with meatballs, sauce, and melty cheese — tiny hero sandwiches!",
    emoji: "🥖",
    color: "#E57373",
    category: "dinner",
    ingredients: [
      ["rolls", "2 mini rolls"],
      ["meatballs", "4 cooked meatballs"],
      ["sauce", "1/4 cup marinara sauce"],
      ["cheese", "2 tbsp shredded cheese"],
    ],
    steps: [
      ["Split the rolls and add meatballs and sauce.", ["rolls", "meatballs", "sauce"]],
      ["Sprinkle cheese on top.", ["cheese"]],
      ["Ask an adult to microwave about 30 seconds until warm and melty.", [], { needsAdult: true, adultReason: "Microwave gets hot!", timerSeconds: 30, timerLabel: "Warm subs" }],
      ["Carefully eat your mini subs!", []],
    ],
  },
  {
    id: "crescent-roll-pizza-pockets",
    title: "Crescent Roll Pizza Pockets",
    cookTimeMins: 15,
    safety: "adult-helper",
    description: "Pepperoni and cheese wrapped in crescent dough — pizza you can hold!",
    emoji: "🍕",
    color: "#EF9A9A",
    category: "dinner",
    ingredients: [
      ["dough", "1 can crescent roll dough"],
      ["pepperoni", "12 pepperoni slices"],
      ["cheese", "4 cheese sticks or strips"],
    ],
    steps: [
      ["Unroll crescent triangles and add pepperoni and cheese.", ["dough", "pepperoni", "cheese"]],
      ["Fold and pinch the edges closed.", []],
      ["Ask an adult to bake at 375°F for about 11 minutes.", [], { needsAdult: true, adultReason: "Hot oven!", timerSeconds: 660, timerLabel: "Bake pockets" }],
      ["Cool a bit, then dunk or bite!", []],
    ],
  },
  {
    id: "sloppy-joe-sliders",
    title: "Sloppy Joe Sliders",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Mini rolls piled with saucy sloppy joe meat and cheese — messily delicious!",
    emoji: "🥪",
    color: "#FF8A65",
    category: "dinner",
    ingredients: [
      ["rolls", "4 mini rolls"],
      ["meat", "1 cup cooked sloppy joe meat"],
      ["cheese", "4 slices of cheese"],
    ],
    steps: [
      ["Split the mini rolls.", ["rolls"]],
      ["Spoon on warm sloppy joe meat.", ["meat"]],
      ["Add cheese and close the sliders.", ["cheese"]],
      ["Wipe your chin and enjoy!", []],
    ],
  },
  {
    id: "baked-potato-bar",
    title: "Baked Potato Bar",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "A fluffy baked potato you load with cheese, sour cream, and bacon bits — build your own!",
    emoji: "🥔",
    color: "#D7CCC8",
    category: "dinner",
    ingredients: [
      ["potato", "1 baked potato"],
      ["cheese", "1/4 cup shredded cheese"],
      ["sour-cream", "2 tbsp sour cream"],
      ["bacon", "1 tbsp bacon bits"],
    ],
    steps: [
      ["Ask an adult to split open the hot baked potato.", ["potato"], { needsAdult: true, adultReason: "Hot potato!" }],
      ["Add cheese so it melts a little.", ["cheese"]],
      ["Dollop sour cream and sprinkle bacon bits.", ["sour-cream", "bacon"]],
      ["Fluff and feast!", []],
    ],
  },
  {
    id: "chicken-nugget-tacos",
    title: "Chicken Nugget Tacos",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Tortillas filled with chicken nuggets, lettuce, and ranch — taco night reinvented!",
    emoji: "🌮",
    color: "#FFCC80",
    category: "dinner",
    ingredients: [
      ["tortillas", "2 small tortillas"],
      ["nuggets", "4–6 cooked chicken nuggets"],
      ["lettuce", "1/2 cup shredded lettuce"],
      ["ranch", "2 tbsp ranch dressing"],
    ],
    steps: [
      ["Warm tortillas if you like, then add nuggets.", ["tortillas", "nuggets"]],
      ["Top with lettuce.", ["lettuce"]],
      ["Drizzle ranch and fold.", ["ranch"]],
      ["Crunch into your nugget tacos!", []],
    ],
  },
  {
    id: "simple-veggie-ramen",
    title: "Simple Veggie Ramen",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Ramen noodles with frozen peas and carrots — cozy bowl, zero fuss!",
    emoji: "🍜",
    color: "#FFAB91",
    category: "dinner",
    ingredients: [
      ["ramen", "1 pack ramen noodles"],
      ["veggies", "1/2 cup frozen peas and carrots"],
    ],
    steps: [
      ["Ask an adult to cook the ramen with the veggies in hot water.", ["ramen", "veggies"], { needsAdult: true, adultReason: "Boiling water is hot!" }],
      ["Stir in the seasoning packet (or use less if you prefer).", []],
      ["Ladle into a bowl.", []],
      ["Slurp carefully!", []],
    ],
  },
  {
    id: "pesto-pasta-peas",
    title: "Pesto Pasta with Peas",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Green pesto pasta tossed with sweet peas — emerald dinner in a flash!",
    emoji: "🍝",
    color: "#A5D6A7",
    category: "dinner",
    ingredients: [
      ["pasta", "1 cup cooked pasta"],
      ["pesto", "2 tbsp pesto"],
      ["peas", "1/2 cup cooked peas"],
    ],
    steps: [
      ["Put warm pasta in a bowl.", ["pasta"]],
      ["Stir in pesto until coated.", ["pesto"]],
      ["Mix in the peas.", ["peas"]],
      ["Twirl and taste!", []],
    ],
  },
  {
    id: "fish-stick-tacos",
    title: "Fish Stick Tacos",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Crispy fish sticks in tortillas with cabbage and mayo — beachy taco night!",
    emoji: "🐟",
    color: "#81D4FA",
    category: "dinner",
    ingredients: [
      ["tortillas", "2 small tortillas"],
      ["fish", "4 cooked fish sticks"],
      ["cabbage", "1/2 cup shredded cabbage"],
      ["mayo", "1 tbsp mayo"],
    ],
    steps: [
      ["Add fish sticks to the tortillas.", ["tortillas", "fish"]],
      ["Top with cabbage.", ["cabbage"]],
      ["Drizzle mayo and fold.", ["mayo"]],
      ["Bite into your fish stick tacos!", []],
    ],
  },
  {
    id: "mini-shepherds-pies",
    title: "Mini Shepherd's Pies",
    cookTimeMins: 15,
    safety: "adult-helper",
    description: "Little cups of beef, corn, and mashed potato tops — comfort food miniatures!",
    emoji: "🥧",
    color: "#BCAAA4",
    category: "dinner",
    ingredients: [
      ["beef", "1 cup cooked ground beef"],
      ["potatoes", "1 cup mashed potatoes"],
      ["corn", "1/2 cup corn"],
    ],
    steps: [
      ["Layer beef and corn in small oven-safe cups or a muffin tin.", ["beef", "corn"]],
      ["Spread mashed potatoes on top.", ["potatoes"]],
      ["Ask an adult to bake at 375°F for 10 minutes.", [], { needsAdult: true, adultReason: "Hot oven!", timerSeconds: 600, timerLabel: "Bake pies" }],
      ["Cool slightly and dig in!", []],
    ],
  },
  {
    id: "taco-cupcakes",
    title: "Taco Cupcakes",
    cookTimeMins: 15,
    safety: "adult-helper",
    description: "Wonton wrappers filled with taco meat and cheese baked like cupcakes — party dinner!",
    emoji: "🧁",
    color: "#FFB74D",
    category: "dinner",
    ingredients: [
      ["wontons", "8 wonton wrappers"],
      ["meat", "1 cup cooked taco meat"],
      ["cheese", "1/2 cup shredded cheese"],
    ],
    steps: [
      ["Press wonton wrappers into muffin cups.", ["wontons"]],
      ["Fill with taco meat and cheese.", ["meat", "cheese"]],
      ["Ask an adult to bake at 375°F for 10 minutes.", [], { needsAdult: true, adultReason: "Hot oven!", timerSeconds: 600, timerLabel: "Bake cupcakes" }],
      ["Cool a minute, then taco-cupcake away!", []],
    ],
  },
  {
    id: "spaghetti-meatball-skewers",
    title: "Spaghetti & Meatball Skewers",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Meatballs and swirled pasta on sticks with sauce for dipping — spaghetti you can hold!",
    emoji: "🍢",
    color: "#E57373",
    category: "dinner",
    ingredients: [
      ["meatballs", "6 cooked meatballs"],
      ["pasta", "1 cup cooked spaghetti"],
      ["sauce", "1/2 cup marinara for dipping"],
    ],
    steps: [
      ["Twirl small nests of spaghetti onto skewers with meatballs.", ["meatballs", "pasta"]],
      ["Arrange on a plate with a cup of sauce.", ["sauce"]],
      ["Dip and munch!", []],
    ],
  },
  {
    id: "grilled-cheese-roll-ups",
    title: "Grilled Cheese Roll-ups",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Bread rolled around cheese and toasted golden — dippable grilled cheese sticks!",
    emoji: "🧀",
    color: "#FFE082",
    category: "dinner",
    ingredients: [
      ["bread", "2 slices of bread"],
      ["cheese", "2 slices of cheese"],
      ["butter", "1 tbsp butter"],
    ],
    steps: [
      ["Flatten bread slightly, add cheese, and roll up tight.", ["bread", "cheese"]],
      ["Ask an adult to butter a pan and toast the roll-ups until golden and melty.", ["butter"], { needsAdult: true, adultReason: "Hot pan!" }],
      ["Cool briefly, then dunk in soup or ketchup if you like!", []],
    ],
  },
  {
    id: "pizza-quesadillas",
    title: "Pizza Quesadillas",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Tortillas filled with cheese, pepperoni, and pizza sauce — pizza meets quesadilla!",
    emoji: "🍕",
    color: "#EF9A9A",
    category: "dinner",
    ingredients: [
      ["tortilla", "1 large tortilla"],
      ["cheese", "1/2 cup shredded cheese"],
      ["pepperoni", "8 pepperoni slices"],
      ["sauce", "2 tbsp pizza sauce"],
    ],
    steps: [
      ["Spread sauce on half the tortilla and add cheese and pepperoni.", ["tortilla", "sauce", "cheese", "pepperoni"]],
      ["Fold and ask an adult to cook in a pan until crispy and melty.", [], { needsAdult: true, adultReason: "Hot pan!" }],
      ["Cut into wedges and serve!", []],
    ],
  },
  {
    id: "hot-dog-mummies",
    title: "Hot Dog Mummies",
    cookTimeMins: 15,
    safety: "adult-helper",
    description: "Hot dogs wrapped in crescent dough strips like mummy bandages — spooky and yummy!",
    emoji: "👻",
    color: "#FFF3E0",
    category: "dinner",
    ingredients: [
      ["hot-dogs", "4 hot dogs"],
      ["dough", "1 can crescent roll dough"],
    ],
    steps: [
      ["Wrap dough strips around each hot dog like bandages, leaving a gap for eyes.", ["hot-dogs", "dough"]],
      ["Ask an adult to bake at 375°F for about 11 minutes.", [], { needsAdult: true, adultReason: "Hot oven!", timerSeconds: 660, timerLabel: "Bake mummies" }],
      ["Add mustard or ketchup eyes and unwrap the fun!", []],
    ],
  },
  {
    id: "chicken-veggie-sheet-pan",
    title: "Chicken & Veggie Sheet Pan",
    cookTimeMins: 20,
    safety: "adult-helper",
    description: "Chicken and broccoli roasted together on one pan — dinner with almost no dishes!",
    emoji: "🥦",
    color: "#AED581",
    category: "dinner",
    ingredients: [
      ["chicken", "2 cups chicken pieces"],
      ["broccoli", "2 cups broccoli florets"],
      ["oil", "1 tbsp oil"],
    ],
    steps: [
      ["Toss chicken and broccoli with oil on a sheet pan.", ["chicken", "broccoli", "oil"]],
      ["Ask an adult to bake at 400°F for 15 minutes until cooked through.", [], { needsAdult: true, adultReason: "Hot oven and raw chicken!", timerSeconds: 900, timerLabel: "Bake sheet pan" }],
      ["Cool slightly and plate your colorful dinner!", []],
    ],
  },
  {
    id: "mini-calzones",
    title: "Mini Calzones",
    cookTimeMins: 15,
    safety: "adult-helper",
    description: "Biscuit dough pockets stuffed with sauce and cheese — pizza folded into a pouch!",
    emoji: "🥟",
    color: "#FFCC80",
    category: "dinner",
    ingredients: [
      ["dough", "1 can biscuit dough"],
      ["sauce", "1/4 cup pizza sauce"],
      ["cheese", "1/2 cup shredded cheese"],
    ],
    steps: [
      ["Flatten biscuits and add a spoon of sauce and cheese.", ["dough", "sauce", "cheese"]],
      ["Fold over and pinch edges sealed.", []],
      ["Ask an adult to bake at 375°F for 10 minutes.", [], { needsAdult: true, adultReason: "Hot oven!", timerSeconds: 600, timerLabel: "Bake calzones" }],
      ["Cool a bit, then bite into melty pockets!", []],
    ],
  },
  {
    id: "bbq-chicken-flatbread",
    title: "BBQ Chicken Flatbread",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Flatbread topped with BBQ sauce, chicken, and cheese — sweet-smoky pizza vibes!",
    emoji: "🫓",
    color: "#FF8A65",
    category: "dinner",
    ingredients: [
      ["flatbread", "1 flatbread"],
      ["bbq", "2 tbsp BBQ sauce"],
      ["chicken", "1/2 cup cooked chicken"],
      ["cheese", "1/2 cup shredded cheese"],
    ],
    steps: [
      ["Spread BBQ sauce on the flatbread.", ["flatbread", "bbq"]],
      ["Add chicken and cheese.", ["chicken", "cheese"]],
      ["Ask an adult to bake at 400°F for 8 minutes.", [], { needsAdult: true, adultReason: "Hot oven!", timerSeconds: 480, timerLabel: "Bake flatbread" }],
      ["Slice and share!", []],
    ],
  },
  {
    id: "mac-cheese-broccoli-trees",
    title: "Mac & Cheese with Broccoli Trees",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Creamy mac and cheese with broccoli florets standing like little trees!",
    emoji: "🌲",
    color: "#C5E1A5",
    category: "dinner",
    ingredients: [
      ["mac", "1 serving prepared mac & cheese"],
      ["broccoli", "1/2 cup cooked broccoli florets"],
    ],
    steps: [
      ["Scoop warm mac & cheese into a bowl.", ["mac"]],
      ["Stand broccoli florets on top like trees.", ["broccoli"]],
      ["Explore the cheesy forest with your fork!", []],
    ],
  },
  {
    id: "turkey-apple-sandwiches",
    title: "Turkey & Apple Sandwiches",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Soft bread with turkey and crisp apple slices — sweet, savory, and crunchy!",
    emoji: "🥪",
    color: "#EF9A9A",
    category: "dinner",
    ingredients: [
      ["bread", "2 slices of bread"],
      ["turkey", "2–3 slices of turkey"],
      ["apple", "A few thin apple slices"],
    ],
    steps: [
      ["Lay turkey on one slice of bread.", ["bread", "turkey"]],
      ["Add apple slices on top.", ["apple"]],
      ["Close the sandwich and cut if you like.", []],
      ["Crunch into lunch (or dinner)!", []],
    ],
  },
  {
    id: "bean-cheese-tostadas",
    title: "Bean & Cheese Tostadas",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Crispy tostadas topped with beans and melty cheese — open-faced taco crunch!",
    emoji: "🌮",
    color: "#FFCC80",
    category: "dinner",
    ingredients: [
      ["tostada", "2 tostada shells"],
      ["beans", "1/2 cup refried beans"],
      ["cheese", "1/4 cup shredded cheese"],
    ],
    steps: [
      ["Spread beans on the tostada shells.", ["tostada", "beans"]],
      ["Sprinkle cheese on top.", ["cheese"]],
      ["Ask an adult to microwave about 20 seconds until the cheese melts.", [], { needsAdult: true, adultReason: "Microwave gets hot!", timerSeconds: 20, timerLabel: "Melt cheese" }],
      ["Crunch carefully!", []],
    ],
  },
  {
    id: "mini-bagel-pizzas",
    title: "Mini Bagel Pizzas",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Mini bagels topped with sauce and cheese — pizza in bagel form!",
    emoji: "🥯",
    color: "#EF9A9A",
    category: "dinner",
    ingredients: [
      ["bagel", "2 mini bagels, split"],
      ["sauce", "1/4 cup pizza sauce"],
      ["cheese", "1/2 cup shredded cheese"],
    ],
    steps: [
      ["Spread sauce on each bagel half.", ["bagel", "sauce"]],
      ["Top with cheese.", ["cheese"]],
      ["Ask an adult to bake or broil until the cheese bubbles.", [], { needsAdult: true, adultReason: "Hot oven!" }],
      ["Cool a minute and munch!", []],
    ],
  },
  {
    id: "ham-cheese-crescent-squares",
    title: "Ham & Cheese Crescent Squares",
    cookTimeMins: 15,
    safety: "adult-helper",
    description: "Ham and cheese tucked in crescent dough and baked into golden squares!",
    emoji: "🟨",
    color: "#FFE0B2",
    category: "dinner",
    ingredients: [
      ["dough", "1 can crescent roll dough"],
      ["ham", "4 slices of ham"],
      ["cheese", "4 slices of cheese"],
    ],
    steps: [
      ["Layer dough, ham, and cheese, then top with more dough.", ["dough", "ham", "cheese"]],
      ["Press edges and cut into squares.", []],
      ["Ask an adult to bake at 375°F for 10 minutes.", [], { needsAdult: true, adultReason: "Hot oven!", timerSeconds: 600, timerLabel: "Bake squares" }],
      ["Cool slightly and serve warm!", []],
    ],
  },
  {
    id: "cold-soba-noodle-salad",
    title: "Cold Soba Noodle Salad",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Chilled noodles with soy-honey dressing and cucumber — cool, slurpy, and fresh!",
    emoji: "🥗",
    color: "#A5D6A7",
    category: "dinner",
    ingredients: [
      ["noodles", "1 cup cooked soba or noodles, cooled"],
      ["soy", "1 tbsp soy sauce"],
      ["honey", "1 tsp honey"],
      ["cucumber", "1/2 cup sliced cucumber"],
    ],
    steps: [
      ["Toss cooled noodles with soy sauce and honey.", ["noodles", "soy", "honey"]],
      ["Add cucumber slices.", ["cucumber"]],
      ["Mix gently and chill if you like.", []],
      ["Slurp your cold noodle salad!", []],
    ],
  },
  {
    id: "pizza-bagels",
    title: "Pizza Bagels",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Bagel halves turned into personal pizzas with sauce and cheese — classic kid dinner!",
    emoji: "🍕",
    color: "#FFAB91",
    category: "dinner",
    ingredients: [
      ["bagel", "1 bagel, split"],
      ["sauce", "2 tbsp pizza sauce"],
      ["cheese", "1/3 cup shredded cheese"],
    ],
    steps: [
      ["Spread sauce on each bagel half.", ["bagel", "sauce"]],
      ["Sprinkle cheese on top.", ["cheese"]],
      ["Ask an adult to bake at 375°F for 10 minutes.", [], { needsAdult: true, adultReason: "Hot oven!", timerSeconds: 600, timerLabel: "Bake bagels" }],
      ["Cool briefly and chomp!", []],
    ],
  },
  {
    id: "ants-on-a-raft",
    title: "Ants on a Raft",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Crackers floating like rafts with tuna salad and raisin ants — snacky dinner fun!",
    emoji: "🐜",
    color: "#D7CCC8",
    category: "dinner",
    ingredients: [
      ["crackers", "8 crackers"],
      ["tuna", "1/2 cup tuna salad"],
      ["raisins", "2 tbsp raisins"],
    ],
    steps: [
      ["Spread tuna salad on each cracker raft.", ["crackers", "tuna"]],
      ["Place raisin ants on top.", ["raisins"]],
      ["Sail them into your mouth!", []],
    ],
  },

  // Dessert 126-150
  {
    id: "no-bake-oreo-truffles",
    title: "No-Bake Oreo Truffles",
    cookTimeMins: 15,
    safety: "adult-helper",
    description: "Crushed Oreos mixed with cream cheese and dipped in chocolate — no-bake candy balls!",
    emoji: "⚫",
    color: "#5D4037",
    category: "dessert",
    ingredients: [
      ["oreos", "20 Oreos, crushed"],
      ["cream-cheese", "4 oz cream cheese, softened"],
      ["chocolate", "1 cup melted chocolate"],
    ],
    steps: [
      ["Mix crushed Oreos with cream cheese until a dough forms.", ["oreos", "cream-cheese"]],
      ["Roll into small balls.", []],
      ["Ask an adult to help dip them in melted chocolate.", ["chocolate"], { needsAdult: true, adultReason: "Melting chocolate can be hot!" }],
      ["Chill until firm.", [], { timerSeconds: 1800, timerLabel: "Chill truffles" }],
      ["Pop one (or two)!", []],
    ],
  },
  {
    id: "cookie-mug-cake",
    title: "Cookie Mug Cake",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "A warm chocolate-chip cookie cake that cooks in a mug — one-minute cookie craving!",
    emoji: "🍪",
    color: "#BCAAA4",
    category: "dessert",
    ingredients: [
      ["butter", "1 tbsp butter, melted"],
      ["sugars", "1 tbsp brown sugar + 1 tbsp white sugar"],
      ["vanilla", "1/4 tsp vanilla"],
      ["yolk", "1 egg yolk"],
      ["flour", "3 tbsp flour"],
      ["chips", "2 tbsp chocolate chips"],
    ],
    steps: [
      ["Mix butter, sugars, vanilla, and egg yolk in a mug.", ["butter", "sugars", "vanilla", "yolk"]],
      ["Stir in flour and chocolate chips.", ["flour", "chips"]],
      ["Ask an adult to microwave for 1 minute.", [], { needsAdult: true, adultReason: "Hot mug and microwave!", timerSeconds: 60, timerLabel: "Microwave cookie" }],
      ["Cool a bit, then dig into gooey cookie cake!", []],
    ],
  },
  {
    id: "fruit-pizza-dessert",
    title: "Fruit Pizza",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "A sugar cookie crust with frosting 'sauce' and colorful fruit toppings — dessert pizza!",
    emoji: "🍕",
    color: "#F8BBD0",
    category: "dessert",
    ingredients: [
      ["cookie", "1 large sugar cookie or cookie crust"],
      ["frosting", "1/4 cup frosting"],
      ["fruit", "Assorted sliced fruit"],
    ],
    steps: [
      ["Spread frosting over the cookie crust.", ["cookie", "frosting"]],
      ["Decorate with fruit like pizza toppings.", ["fruit"]],
      ["Slice into wedges and share!", []],
    ],
  },
  {
    id: "apricot-energy-bites",
    title: "Apricot Energy Bites",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Chewy bites of dried apricot, coconut, and honey — sweet fuel for play!",
    emoji: "🟠",
    color: "#FFB74D",
    category: "dessert",
    ingredients: [
      ["apricots", "1 cup dried apricots"],
      ["coconut", "1/2 cup shredded coconut"],
      ["honey", "2 tbsp honey"],
    ],
    steps: [
      ["Ask an adult to help chop or pulse the apricots until sticky.", ["apricots"], { needsAdult: true, adultReason: "Chopping or food processor needs adult help!" }],
      ["Mix with coconut and honey.", ["coconut", "honey"]],
      ["Roll into small energy bites.", []],
      ["Snack when you need a boost!", []],
    ],
  },
  {
    id: "banana-nice-cream",
    title: "Banana Nice Cream",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Frozen bananas blended into creamy soft-serve — ice cream with no dairy drama!",
    emoji: "🍌",
    color: "#FFE566",
    category: "dessert",
    ingredients: [
      ["bananas", "2 frozen bananas"],
      ["milk", "2–4 tbsp milk"],
    ],
    steps: [
      ["Put frozen bananas and a splash of milk in the blender.", ["bananas", "milk"]],
      ["Ask an adult to blend until creamy like soft-serve.", [], { needsAdult: true, adultReason: "Blenders need adult hands!", timerSeconds: 30, timerLabel: "Blend nice cream" }],
      ["Scoop into a bowl and eat right away!", []],
    ],
  },
  {
    id: "strawberry-santas",
    title: "Strawberry Santas",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Strawberries dressed as tiny Santas with whipped cream hats — holiday snack magic!",
    emoji: "🎅",
    color: "#EF9A9A",
    category: "dessert",
    ingredients: [
      ["strawberries", "8 strawberries"],
      ["cream", "Whipped cream"],
    ],
    steps: [
      ["Ask an adult to cut the tops off strawberries for hats.", ["strawberries"], { needsAdult: true, adultReason: "Cutting needs a knife!" }],
      ["Pipe or spoon whipped cream on the berry body.", ["cream"]],
      ["Set the strawberry top back on as a hat.", []],
      ["Make a cream beard if you like, then display and eat!", []],
    ],
  },
  {
    id: "chocolate-dipped-strawberries",
    title: "Chocolate Dipped Strawberries",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Juicy strawberries dunked in melted chocolate — fancy fruit dessert!",
    emoji: "🍓",
    color: "#F48FB1",
    category: "dessert",
    ingredients: [
      ["strawberries", "10 strawberries"],
      ["chips", "1 cup chocolate chips"],
    ],
    steps: [
      ["Ask an adult to melt the chocolate chips.", ["chips"], { needsAdult: true, adultReason: "Melting chocolate can be hot!", timerSeconds: 30, timerLabel: "Melt chocolate" }],
      ["Dip each strawberry halfway into the chocolate.", ["strawberries"]],
      ["Set on wax paper to firm up.", []],
      ["Bite into chocolate-berry bliss!", []],
    ],
  },
  {
    id: "graham-cracker-houses",
    title: "Graham Cracker Houses",
    cookTimeMins: 15,
    safety: "kid-solo",
    description: "Mini houses built from graham crackers, frosting glue, and candy decorations!",
    emoji: "🏠",
    color: "#D7CCC8",
    category: "dessert",
    ingredients: [
      ["graham", "4–6 graham crackers"],
      ["frosting", "1/2 cup frosting"],
      ["candies", "Assorted candies for decorating"],
    ],
    steps: [
      ["Use frosting as glue to stand graham crackers into a house shape.", ["graham", "frosting"]],
      ["Decorate with candies.", ["candies"]],
      ["Admire your house, then nibble the walls!", []],
    ],
  },
  {
    id: "no-bake-lemon-bars",
    title: "No-Bake Lemon Bars",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Zingy lemon filling over graham crumbs — bright bars that chill, not bake!",
    emoji: "🍋",
    color: "#FFF59D",
    category: "dessert",
    ingredients: [
      ["crumbs", "1 cup graham cracker crumbs"],
      ["milk", "1/2 cup sweetened condensed milk"],
      ["lemon", "1/4 cup lemon juice"],
    ],
    steps: [
      ["Press graham crumbs into a small pan as the crust.", ["crumbs"]],
      ["Mix condensed milk and lemon juice, then pour over the crust.", ["milk", "lemon"]],
      ["Chill until set.", [], { timerSeconds: 3600, timerLabel: "Chill bars" }],
      ["Cut into squares and taste the tang!", []],
    ],
  },
  {
    id: "apple-nachos-caramel",
    title: "Apple Nachos with Caramel",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Apple slices drizzled with caramel and mini chips — sweet nacho vibes!",
    emoji: "🍎",
    color: "#FFAB91",
    category: "dessert",
    ingredients: [
      ["apple", "1 apple, sliced"],
      ["caramel", "2 tbsp caramel sauce"],
      ["chips", "2 tbsp mini chocolate chips"],
    ],
    steps: [
      ["Arrange apple slices on a plate.", ["apple"]],
      ["Drizzle caramel over the top.", ["caramel"]],
      ["Sprinkle mini chips.", ["chips"]],
      ["Scoop up apple nachos!", []],
    ],
  },
  {
    id: "pb-celery-butterflies",
    title: "Peanut Butter Celery Butterflies",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Celery sticks with peanut butter bodies and pretzel wings — snack insects!",
    emoji: "🦋",
    color: "#A5D6A7",
    category: "dessert",
    ingredients: [
      ["celery", "4 celery sticks"],
      ["pb", "1/4 cup peanut butter (or alternative)"],
      ["pretzels", "8 pretzel twists"],
      ["raisins", "A few raisins for eyes"],
    ],
    steps: [
      ["Fill celery sticks with peanut butter.", ["celery", "pb"]],
      ["Press pretzel twists on the sides for wings.", ["pretzels"]],
      ["Add raisin eyes.", ["raisins"]],
      ["Let your butterflies fly into your mouth!", []],
    ],
  },
  {
    id: "watermelon-pizza",
    title: "Watermelon Pizza",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "A watermelon round topped with blueberries and feta or coconut — juicy fruit pizza!",
    emoji: "🍉",
    color: "#EF9A9A",
    category: "dessert",
    ingredients: [
      ["watermelon", "1 thick watermelon round"],
      ["blueberries", "1/2 cup blueberries"],
      ["topping", "2 tbsp feta or shredded coconut"],
    ],
    steps: [
      ["Place the watermelon round on a plate as your crust.", ["watermelon"]],
      ["Scatter blueberries on top.", ["blueberries"]],
      ["Sprinkle feta or coconut.", ["topping"]],
      ["Slice into wedges and share!", []],
    ],
  },
  {
    id: "chocolate-bark-nuts",
    title: "Chocolate Bark with Nuts",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Melted chocolate spread thin and studded with nuts — snap-apart candy!",
    emoji: "🍫",
    color: "#6D4C41",
    category: "dessert",
    ingredients: [
      ["chocolate", "1 cup melted chocolate"],
      ["nuts", "1/2 cup chopped nuts"],
    ],
    steps: [
      ["Ask an adult to melt the chocolate and spread it on wax paper.", ["chocolate"], { needsAdult: true, adultReason: "Melting chocolate can be hot!" }],
      ["Sprinkle nuts all over.", ["nuts"]],
      ["Freeze until hard.", [], { timerSeconds: 3600, timerLabel: "Freeze bark" }],
      ["Break into pieces and crunch!", []],
    ],
  },
  {
    id: "no-bake-brownie-bites",
    title: "No-Bake Brownie Bites",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Walnuts, dates, and cocoa rolled into fudgy bites — brownie taste, no oven!",
    emoji: "🟫",
    color: "#5D4037",
    category: "dessert",
    ingredients: [
      ["walnuts", "1 cup walnuts"],
      ["dates", "1 cup pitted dates"],
      ["cocoa", "2 tbsp cocoa powder"],
    ],
    steps: [
      ["Ask an adult to pulse walnuts, dates, and cocoa in a food processor until sticky.", ["walnuts", "dates", "cocoa"], { needsAdult: true, adultReason: "Food processor needs adult hands!" }],
      ["Roll into small brownie bites.", []],
      ["Chill if you like, then enjoy!", []],
    ],
  },
  {
    id: "fruit-rice-paper-rolls",
    title: "Fruit Rice Paper Rolls",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Soft rice paper wrapped around strawberries, mango, and mint — fresh fruit spring rolls!",
    emoji: "🥭",
    color: "#FFCC80",
    category: "dessert",
    ingredients: [
      ["rice-paper", "4 rice paper wrappers"],
      ["strawberries", "1/2 cup sliced strawberries"],
      ["mango", "1/2 cup sliced mango"],
      ["mint", "A few mint leaves"],
    ],
    steps: [
      ["Dip rice paper in water until soft.", ["rice-paper"]],
      ["Add strawberries, mango, and mint in the center.", ["strawberries", "mango", "mint"]],
      ["Roll up tightly like a burrito.", []],
      ["Bite into your fruity rolls!", []],
    ],
  },
  {
    id: "yogurt-melts",
    title: "Yogurt Melts",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Tiny dots of flavored yogurt frozen into melt-in-your-mouth bites!",
    emoji: "⚪",
    color: "#F8BBD0",
    category: "dessert",
    ingredients: [
      ["yogurt", "1 cup flavored yogurt"],
    ],
    steps: [
      ["Drop small spoonfuls of yogurt onto a lined tray.", ["yogurt"]],
      ["Freeze until solid.", [], { timerSeconds: 7200, timerLabel: "Freeze melts" }],
      ["Pop them off and melt them in your mouth!", []],
    ],
  },
  {
    id: "trail-mix-popcorn",
    title: "Trail Mix Popcorn",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Popcorn mixed with chocolate chips and cranberries — movie snack meets trail mix!",
    emoji: "🍿",
    color: "#FFE082",
    category: "dessert",
    ingredients: [
      ["popcorn", "4 cups popcorn"],
      ["chips", "1/4 cup chocolate chips"],
      ["cranberries", "1/4 cup dried cranberries"],
    ],
    steps: [
      ["Pour popcorn into a big bowl.", ["popcorn"]],
      ["Add chocolate chips and cranberries.", ["chips", "cranberries"]],
      ["Toss and munch your trail mix popcorn!", []],
    ],
  },
  {
    id: "mini-fruit-tarts",
    title: "Mini Fruit Tarts",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Ready tart shells filled with pudding and topped with fruit — bakery treats at home!",
    emoji: "🥧",
    color: "#F48FB1",
    category: "dessert",
    ingredients: [
      ["shells", "4 mini tart shells"],
      ["pudding", "1 cup prepared pudding"],
      ["fruit", "Assorted fruit for topping"],
    ],
    steps: [
      ["Spoon pudding into each tart shell.", ["shells", "pudding"]],
      ["Decorate with fruit on top.", ["fruit"]],
      ["Chill briefly if you want, then serve!", []],
    ],
  },
  {
    id: "chocolate-covered-bananas",
    title: "Chocolate Covered Bananas",
    cookTimeMins: 10,
    safety: "adult-helper",
    description: "Banana halves on sticks dipped in chocolate and frozen — icy banana pops!",
    emoji: "🍌",
    color: "#FFE566",
    category: "dessert",
    ingredients: [
      ["banana", "2 bananas"],
      ["chocolate", "1 cup melted chocolate"],
      ["sticks", "Popsicle sticks"],
    ],
    steps: [
      ["Peel bananas, cut in half, and insert sticks.", ["banana", "sticks"]],
      ["Ask an adult to help dip them in melted chocolate.", ["chocolate"], { needsAdult: true, adultReason: "Melting chocolate can be hot!" }],
      ["Freeze until firm.", [], { timerSeconds: 3600, timerLabel: "Freeze pops" }],
      ["Peel off any paper and enjoy!", []],
    ],
  },
  {
    id: "no-bake-granola-bars",
    title: "No-Bake Granola Bars",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Oats, honey, and peanut butter pressed into chewy bars — no oven needed!",
    emoji: "🍫",
    color: "#D7CCC8",
    category: "dessert",
    ingredients: [
      ["oats", "2 cups oats"],
      ["honey", "1/3 cup honey"],
      ["pb", "1/2 cup peanut butter (or alternative)"],
    ],
    steps: [
      ["Mix oats, honey, and peanut butter until sticky.", ["oats", "honey", "pb"]],
      ["Press firmly into a lined pan.", []],
      ["Chill until firm.", [], { timerSeconds: 3600, timerLabel: "Chill bars" }],
      ["Cut into bars and pack for later!", []],
    ],
  },
  {
    id: "pbj-bites",
    title: "PB&J Bites",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Crackers sandwiched with peanut butter and jelly — mini PB&J in two bites!",
    emoji: "🍪",
    color: "#FFCC80",
    category: "dessert",
    ingredients: [
      ["crackers", "12 crackers"],
      ["pb", "3 tbsp peanut butter (or alternative)"],
      ["jelly", "3 tbsp jelly"],
    ],
    steps: [
      ["Spread peanut butter on half the crackers.", ["crackers", "pb"]],
      ["Spread jelly on the other half.", ["jelly"]],
      ["Press into sandwiches.", []],
      ["Pop the bites!", []],
    ],
  },
  {
    id: "fruit-cheese-skewers",
    title: "Fruit & Cheese Skewers",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Grapes and cheese cubes on sticks — sweet, salty, and skewered!",
    emoji: "🍢",
    color: "#CE93D8",
    category: "dessert",
    ingredients: [
      ["grapes", "1 cup grapes"],
      ["cheese", "1 cup cheese cubes"],
    ],
    steps: [
      ["Thread grapes and cheese cubes onto skewers.", ["grapes", "cheese"]],
      ["Arrange on a plate.", []],
      ["Pull off bites and enjoy!", []],
    ],
  },
  {
    id: "caramel-popcorn",
    title: "Caramel Popcorn",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Popcorn tossed in gooey caramel sauce — fairground snack at home!",
    emoji: "🍿",
    color: "#FFB74D",
    category: "dessert",
    ingredients: [
      ["popcorn", "6 cups popcorn"],
      ["caramel", "1/3 cup caramel sauce"],
    ],
    steps: [
      ["Put popcorn in a big bowl.", ["popcorn"]],
      ["Drizzle caramel sauce and toss to coat.", ["caramel"]],
      ["Spread out if sticky, then munch!", []],
    ],
  },
  {
    id: "no-bake-coconut-macaroons",
    title: "No-Bake Coconut Macaroons",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Shredded coconut and condensed milk shaped into chewy little mounds!",
    emoji: "🥥",
    color: "#FFF8E1",
    category: "dessert",
    ingredients: [
      ["coconut", "2 cups shredded coconut"],
      ["milk", "1/2 cup sweetened condensed milk"],
    ],
    steps: [
      ["Mix coconut and condensed milk until sticky.", ["coconut", "milk"]],
      ["Scoop into small mounds on wax paper.", []],
      ["Let them set a bit, then enjoy!", []],
    ],
  },
  {
    id: "pudding-dirt-cups-beach",
    title: "Pudding Dirt Cups",
    cookTimeMins: 10,
    safety: "kid-solo",
    description: "Vanilla pudding with crushed golden Oreos as sand and gummy bears at the beach!",
    emoji: "🏖️",
    color: "#FFE082",
    category: "dessert",
    ingredients: [
      ["pudding", "2 cups vanilla pudding"],
      ["oreos", "1 cup crushed golden Oreos"],
      ["gummies", "Gummy bears"],
    ],
    steps: [
      ["Spoon pudding into cups.", ["pudding"]],
      ["Top with crushed golden Oreos like sand.", ["oreos"]],
      ["Add gummy bears for beach friends.", ["gummies"]],
      ["Dig into your beach cups!", []],
    ],
  },

  // Drinks 151-175
  {
    id: "virgin-mojito",
    title: "Virgin Mojito",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Sparkling water with lime, mint, and a touch of sugar — a fizzy mocktail!",
    emoji: "🍹",
    color: "#A5D6A7",
    category: "drinks",
    ingredients: [
      ["sparkling", "1 cup sparkling water"],
      ["lime", "1/2 lime, juiced or sliced"],
      ["mint", "4–6 mint leaves"],
      ["sugar", "1 tsp sugar"],
    ],
    steps: [
      ["Muddle mint and sugar gently in a glass.", ["mint", "sugar"]],
      ["Add lime and sparkling water.", ["lime", "sparkling"]],
      ["Stir, add ice if you like, and sip!", []],
    ],
  },
  {
    id: "simple-mango-lassi",
    title: "Simple Mango Lassi",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Creamy mango, yogurt, and milk blended smooth — a sunny Indian-inspired sip!",
    emoji: "🥭",
    color: "#FFB74D",
    category: "drinks",
    ingredients: [
      ["mango", "1/2 cup mango pulp"],
      ["yogurt", "1/2 cup yogurt"],
      ["milk", "1/2 cup milk"],
    ],
    steps: [
      ["Put mango pulp, yogurt, and milk in the blender.", ["mango", "yogurt", "milk"]],
      ["Ask an adult to blend until smooth.", [], { needsAdult: true, adultReason: "Blenders need adult hands!", timerSeconds: 30, timerLabel: "Blend lassi" }],
      ["Pour into a glass and enjoy cold!", []],
    ],
  },
  {
    id: "shirley-temple",
    title: "Shirley Temple",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Bubbly lemon-lime soda with grenadine and a cherry on top — classic kid mocktail!",
    emoji: "🍒",
    color: "#F48FB1",
    category: "drinks",
    ingredients: [
      ["soda", "1 cup lemon-lime soda"],
      ["grenadine", "1–2 tbsp grenadine"],
      ["cherry", "1 maraschino cherry"],
    ],
    steps: [
      ["Pour soda into a glass with ice.", ["soda"]],
      ["Stir in grenadine.", ["grenadine"]],
      ["Top with a cherry and sip fancy!", ["cherry"]],
    ],
  },
  {
    id: "arnold-palmer",
    title: "Arnold Palmer",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Half iced tea, half lemonade — the ultimate thirst-quencher combo!",
    emoji: "⛳",
    color: "#FFE082",
    category: "drinks",
    ingredients: [
      ["tea", "1/2 cup iced tea"],
      ["lemonade", "1/2 cup lemonade"],
    ],
    steps: [
      ["Pour iced tea into a glass.", ["tea"]],
      ["Add lemonade and stir.", ["lemonade"]],
      ["Add ice and sip on the green!", []],
    ],
  },
  {
    id: "fruit-infused-ice-cubes",
    title: "Fruit Infused Ice Cubes",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Water frozen with fruit bits inside — ice cubes that flavor your drink!",
    emoji: "🧊",
    color: "#81D4FA",
    category: "drinks",
    ingredients: [
      ["water", "1 cup water"],
      ["fruit", "Chopped fruit pieces"],
    ],
    steps: [
      ["Drop fruit pieces into an ice cube tray.", ["fruit"]],
      ["Fill with water.", ["water"]],
      ["Freeze until solid.", [], { timerSeconds: 10800, timerLabel: "Freeze cubes" }],
      ["Pop into drinks for fruity chill!", []],
    ],
  },
  {
    id: "warm-spiced-apple-juice",
    title: "Warm Spiced Apple Juice",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Warm apple juice with a pinch of nutmeg — cozy cider vibes in a mug!",
    emoji: "🍎",
    color: "#FFCC80",
    category: "drinks",
    ingredients: [
      ["juice", "1 cup apple juice"],
      ["nutmeg", "A pinch of nutmeg"],
    ],
    steps: [
      ["Pour apple juice into a mug and add nutmeg.", ["juice", "nutmeg"]],
      ["Ask an adult to microwave for 1 minute until warm.", [], { needsAdult: true, adultReason: "Hot drinks need adult help!", timerSeconds: 60, timerLabel: "Warm juice" }],
      ["Sip carefully!", []],
    ],
  },
  {
    id: "blueberry-yogurt-drink",
    title: "Blueberry Yogurt Drink",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Milk shaken with blueberry yogurt — a creamy purple sip!",
    emoji: "🫐",
    color: "#CE93D8",
    category: "drinks",
    ingredients: [
      ["milk", "1/2 cup milk"],
      ["yogurt", "1/2 cup blueberry yogurt"],
    ],
    steps: [
      ["Stir or shake milk and blueberry yogurt together.", ["milk", "yogurt"]],
      ["Pour into a glass.", []],
      ["Drink your purple power!", []],
    ],
  },
  {
    id: "peppermint-hot-chocolate",
    title: "Peppermint Hot Chocolate",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Hot cocoa stirred with a candy cane — minty, chocolatey, and magical!",
    emoji: "☕",
    color: "#EF9A9A",
    category: "drinks",
    ingredients: [
      ["cocoa", "1 mug prepared hot cocoa"],
      ["cane", "1 candy cane"],
    ],
    steps: [
      ["Get a warm mug of hot cocoa (adults can help make it).", ["cocoa"]],
      ["Stir with a candy cane until it melts a little.", ["cane"]],
      ["Sip the minty chocolate!", []],
    ],
  },
  {
    id: "peach-ginger-fizz",
    title: "Peach & Ginger Fizz",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Peach juice topped with spicy-sweet ginger ale — bubbly and bright!",
    emoji: "🍑",
    color: "#FFAB91",
    category: "drinks",
    ingredients: [
      ["peach", "1/2 cup peach juice"],
      ["ginger-ale", "1/2 cup ginger ale"],
    ],
    steps: [
      ["Pour peach juice into a glass.", ["peach"]],
      ["Top with ginger ale and stir gently.", ["ginger-ale"]],
      ["Add ice and fizz away!", []],
    ],
  },
  {
    id: "cherry-limeade",
    title: "Cherry Limeade",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Tangy lime and sweet cherry syrup over ice — a soda-shop classic!",
    emoji: "🍒",
    color: "#F48FB1",
    category: "drinks",
    ingredients: [
      ["water", "1 cup water"],
      ["lime", "2 tbsp lime juice"],
      ["syrup", "2 tbsp cherry syrup"],
      ["ice", "Ice"],
    ],
    steps: [
      ["Mix water, lime juice, and cherry syrup.", ["water", "lime", "syrup"]],
      ["Pour over ice.", ["ice"]],
      ["Stir and sip!", []],
    ],
  },
  {
    id: "banana-date-smoothie",
    title: "Banana & Date Smoothie",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Banana and sweet dates blended with milk — naturally candy-like!",
    emoji: "🍌",
    color: "#FFE082",
    category: "drinks",
    ingredients: [
      ["banana", "1 banana"],
      ["dates", "3 pitted dates"],
      ["milk", "1 cup milk"],
    ],
    steps: [
      ["Put banana, dates, and milk in the blender.", ["banana", "dates", "milk"]],
      ["Ask an adult to blend until smooth.", [], { needsAdult: true, adultReason: "Blenders need adult hands!", timerSeconds: 30, timerLabel: "Blend smoothie" }],
      ["Pour and enjoy!", []],
    ],
  },
  {
    id: "cucumber-mint-refresher",
    title: "Cucumber & Mint Refresher",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Cool water infused with cucumber and mint — spa day in a glass!",
    emoji: "🥒",
    color: "#C5E1A5",
    category: "drinks",
    ingredients: [
      ["water", "2 cups water"],
      ["cucumber", "A few cucumber slices"],
      ["mint", "4 mint leaves"],
    ],
    steps: [
      ["Add cucumber and mint to a pitcher of water.", ["water", "cucumber", "mint"]],
      ["Let it steep so the flavors bloom.", [], { timerSeconds: 600, timerLabel: "Steep refresher" }],
      ["Pour over ice and feel refreshed!", []],
    ],
  },
  {
    id: "frozen-hot-chocolate",
    title: "Frozen Hot Chocolate",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Milk, cocoa mix, and ice blended into a frosty chocolate shake!",
    emoji: "❄️",
    color: "#BCAAA4",
    category: "drinks",
    ingredients: [
      ["milk", "1 cup milk"],
      ["cocoa", "2 tbsp hot cocoa mix"],
      ["ice", "1 cup ice"],
    ],
    steps: [
      ["Put milk, cocoa mix, and ice in the blender.", ["milk", "cocoa", "ice"]],
      ["Ask an adult to blend until frosty and smooth.", [], { needsAdult: true, adultReason: "Blenders need adult hands!", timerSeconds: 30, timerLabel: "Blend frozen cocoa" }],
      ["Pour into a glass and sip cold!", []],
    ],
  },
  {
    id: "tropical-fruit-punch",
    title: "Tropical Fruit Punch",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Pineapple, orange, and mango juices mixed into a vacation in a cup!",
    emoji: "🏝️",
    color: "#FFCC80",
    category: "drinks",
    ingredients: [
      ["pineapple", "1/3 cup pineapple juice"],
      ["orange", "1/3 cup orange juice"],
      ["mango", "1/3 cup mango juice"],
    ],
    steps: [
      ["Pour all three juices into a pitcher or glass.", ["pineapple", "orange", "mango"]],
      ["Stir well.", []],
      ["Add ice and pretend you're at the beach!", []],
    ],
  },
  {
    id: "iced-vanilla-milk",
    title: "Iced Vanilla Milk",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Cold milk sweetened with vanilla and sugar over ice — simple and dreamy!",
    emoji: "🥛",
    color: "#FFF8E1",
    category: "drinks",
    ingredients: [
      ["milk", "1 cup milk"],
      ["vanilla", "1/2 tsp vanilla"],
      ["sugar", "1 tsp sugar"],
      ["ice", "Ice"],
    ],
    steps: [
      ["Stir milk, vanilla, and sugar until dissolved.", ["milk", "vanilla", "sugar"]],
      ["Pour over ice.", ["ice"]],
      ["Sip your vanilla cloud!", []],
    ],
  },
  {
    id: "strawberry-mint-water",
    title: "Strawberry Mint Water",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Fresh water with smashed strawberries and mint — lightly sweet and garden-fresh!",
    emoji: "🍓",
    color: "#F8BBD0",
    category: "drinks",
    ingredients: [
      ["water", "2 cups water"],
      ["strawberry", "4 strawberries, sliced"],
      ["mint", "4 mint leaves"],
    ],
    steps: [
      ["Add strawberries and mint to water.", ["water", "strawberry", "mint"]],
      ["Gently mash a few berries to release juice.", []],
      ["Pour over ice and sip!", []],
    ],
  },
  {
    id: "pineapple-ginger-ale",
    title: "Pineapple Ginger Ale",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Pineapple juice topped with ginger ale — tropical fizz!",
    emoji: "🍍",
    color: "#FFE082",
    category: "drinks",
    ingredients: [
      ["pineapple", "1/2 cup pineapple juice"],
      ["ginger-ale", "1/2 cup ginger ale"],
    ],
    steps: [
      ["Pour pineapple juice into a glass.", ["pineapple"]],
      ["Top with ginger ale and stir gently.", ["ginger-ale"]],
      ["Add ice and enjoy the bubbles!", []],
    ],
  },
  {
    id: "green-apple-slushie",
    title: "Green Apple Slushie",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Apple juice blended with ice into a frosty green slush — optional food coloring for wow!",
    emoji: "🍏",
    color: "#AED581",
    category: "drinks",
    ingredients: [
      ["juice", "1 cup apple juice"],
      ["coloring", "Optional drop of green food coloring"],
      ["ice", "1–2 cups ice"],
    ],
    steps: [
      ["Put apple juice, ice, and optional coloring in the blender.", ["juice", "ice", "coloring"]],
      ["Ask an adult to blend until slushy.", [], { needsAdult: true, adultReason: "Blenders need adult hands!", timerSeconds: 30, timerLabel: "Blend slushie" }],
      ["Scoop into a cup and dig in with a spoon!", []],
    ],
  },
  {
    id: "blackberry-fizz",
    title: "Blackberry Fizz",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Blackberry juice topped with sparkling water — deep purple bubbles!",
    emoji: "🫧",
    color: "#CE93D8",
    category: "drinks",
    ingredients: [
      ["blackberry", "1/2 cup blackberry juice"],
      ["sparkling", "1/2 cup sparkling water"],
    ],
    steps: [
      ["Pour blackberry juice into a glass.", ["blackberry"]],
      ["Top with sparkling water.", ["sparkling"]],
      ["Stir gently and sip the fizz!", []],
    ],
  },
  {
    id: "coconut-water-punch",
    title: "Coconut Water Punch",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Coconut water mixed with pineapple juice — hydrating island punch!",
    emoji: "🥥",
    color: "#B2EBF2",
    category: "drinks",
    ingredients: [
      ["coconut", "1/2 cup coconut water"],
      ["pineapple", "1/2 cup pineapple juice"],
    ],
    steps: [
      ["Mix coconut water and pineapple juice.", ["coconut", "pineapple"]],
      ["Pour over ice.", []],
      ["Drink your island punch!", []],
    ],
  },
  {
    id: "spiced-pear-juice",
    title: "Spiced Pear Juice",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Pear juice stirred with a pinch of cinnamon — soft, sweet, and cozy!",
    emoji: "🍐",
    color: "#E6EE9C",
    category: "drinks",
    ingredients: [
      ["pear", "1 cup pear juice"],
      ["cinnamon", "A pinch of cinnamon"],
    ],
    steps: [
      ["Pour pear juice into a glass.", ["pear"]],
      ["Stir in cinnamon.", ["cinnamon"]],
      ["Sip your spiced pear treat!", []],
    ],
  },
  {
    id: "melon-mint-smoothie",
    title: "Melon & Mint Smoothie",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Honeydew, mint, and yogurt blended into a cool green smoothie!",
    emoji: "🍈",
    color: "#C5E1A5",
    category: "drinks",
    ingredients: [
      ["melon", "1 cup honeydew chunks"],
      ["mint", "4 mint leaves"],
      ["yogurt", "1/2 cup yogurt"],
    ],
    steps: [
      ["Put honeydew, mint, and yogurt in the blender.", ["melon", "mint", "yogurt"]],
      ["Ask an adult to blend until smooth.", [], { needsAdult: true, adultReason: "Blenders need adult hands!", timerSeconds: 30, timerLabel: "Blend smoothie" }],
      ["Pour and cool down!", []],
    ],
  },
  {
    id: "vanilla-steamer",
    title: "Vanilla Steamer",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Warm milk sweetened with sugar and vanilla — a cafe steamer at home!",
    emoji: "☕",
    color: "#FFF8E1",
    category: "drinks",
    ingredients: [
      ["milk", "1 cup milk"],
      ["sugar", "1 tsp sugar"],
      ["vanilla", "1/2 tsp vanilla"],
    ],
    steps: [
      ["Mix milk, sugar, and vanilla in a mug.", ["milk", "sugar", "vanilla"]],
      ["Ask an adult to microwave for 1 minute until warm.", [], { needsAdult: true, adultReason: "Hot drinks need adult help!", timerSeconds: 60, timerLabel: "Warm steamer" }],
      ["Sip slowly!", []],
    ],
  },
  {
    id: "berry-sparkler",
    title: "Berry Sparkler",
    cookTimeMins: 5,
    safety: "kid-solo",
    description: "Berry juice topped with sparkling water — a jewel-colored sparkler!",
    emoji: "✨",
    color: "#F48FB1",
    category: "drinks",
    ingredients: [
      ["berry", "1/2 cup berry juice"],
      ["sparkling", "1/2 cup sparkling water"],
    ],
    steps: [
      ["Pour berry juice into a glass.", ["berry"]],
      ["Top with sparkling water.", ["sparkling"]],
      ["Watch it sparkle, then sip!", []],
    ],
  },
  {
    id: "rainbow-layered-juice",
    title: "Rainbow Layered Juice",
    cookTimeMins: 5,
    safety: "adult-helper",
    description: "Grenadine, orange juice, and blue sports drink layered into a rainbow glass!",
    emoji: "🌈",
    color: "#90CAF9",
    category: "drinks",
    ingredients: [
      ["grenadine", "2 tbsp grenadine"],
      ["orange", "1/3 cup orange juice"],
      ["blue", "1/3 cup blue sports drink"],
    ],
    steps: [
      ["Pour grenadine into the bottom of a tall glass.", ["grenadine"]],
      ["Ask an adult to help slowly layer orange juice over the back of a spoon.", ["orange"], { needsAdult: true, adultReason: "Layering takes a careful pour!" }],
      ["Slowly add the blue sports drink the same way.", ["blue"]],
      ["Admire the rainbow, then sip through a straw!", []],
    ],
  },
];

function escape(s) {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function stepToTs(step, idx) {
  const [instruction, ingredientIds = [], extra = {}] = step;
  const lines = [
    `      {`,
    `        id: "s${idx + 1}",`,
    `        instruction: "${escape(instruction)}",`,
  ];
  if (extra.timerSeconds) {
    lines.push(`        timerSeconds: ${extra.timerSeconds},`);
    if (extra.timerLabel) lines.push(`        timerLabel: "${escape(extra.timerLabel)}",`);
  }
  lines.push(
    `        ingredientIds: [${ingredientIds.map((id) => `"${id}"`).join(", ")}],`,
  );
  if (extra.needsAdult) {
    lines.push(`        needsAdult: true,`);
    if (extra.adultReason) lines.push(`        adultReason: "${escape(extra.adultReason)}",`);
  }
  lines.push(`      },`);
  return lines.join("\n");
}

function recipeToTs(r) {
  const pattern =
    "radial-gradient(circle at 40% 40%, rgba(255,255,255,0.35) 0 14%, transparent 15%)";
  return `  {
    id: "${r.id}",
    title: "${escape(r.title)}",
    cookTimeMins: ${r.cookTimeMins},
    safety: "${r.safety}",
    description: "${escape(r.description)}",
    emoji: "${r.emoji}",
    placeholderColor: "${r.color}",
    pattern: "${pattern}",
    suggestedCookbook: "${r.category}",
    baseServings: 1,
    imageSrc: "/recipes/${r.id}.svg",
    ingredients: [
${r.ingredients.map(([id, name]) => `      { id: "${id}", name: "${escape(name)}" },`).join("\n")}
    ],
    steps: [
${r.steps.map((s, i) => stepToTs(s, i)).join("\n")}
    ],
  },`;
}

const outTs = `import type { Recipe } from "./types";

/** Extra mini-chef recipes (batch 3) */
export const MORE_RECIPES_BATCH3: Recipe[] = [
${recipes.map(recipeToTs).join("\n")}
];
`;

fs.writeFileSync(path.join("lib", "more-recipes-batch3.ts"), outTs);

const dir = path.join("public", "recipes");
fs.mkdirSync(dir, { recursive: true });

for (const r of recipes) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 520 520">
  <rect width="520" height="520" fill="${r.color}"/>
  <circle cx="260" cy="250" r="120" fill="rgba(255,255,255,0.35)"/>
  <text x="260" y="280" text-anchor="middle" font-size="120">${r.emoji}</text>
</svg>
`;
  fs.writeFileSync(path.join(dir, `${r.id}.svg`), svg);
}

console.log(`Wrote ${recipes.length} recipes + SVGs`);
